### ISSUE TITLE
ether_sky - A liquidator has the ability to liquidate any amount between half and the entire position that is being liquidated.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#100]
ether_sky

medium

# A liquidator has the ability to liquidate any amount between half and the entire position that is being liquidated.

## Summary
Regarding the `maximum liquidatable position size`, I came across the following information in the documentation.
```solidity
When the account value falls below the maintenance margin requirement but remains above half of the maintenance margin 
requirement, the liquidator can only liquidate up to half of the position size. 
Otherwise, liquidator will liquidate the entire position.
```
I understood this as meaning the `liquidator` can either liquidate up to half of the `position size` under certain conditions or liquidate the entire `position`.

Also please take a look at the code below.
```solidity
function getLiquidatablePositionSize(MaintenanceMarginProfile memory self) internal view returns (int256) {
    // Liquidate the entire position if its value is small enough
    // to prevent tiny positions left in the system
    uint256 positionValueAbs = self.positionSize.abs().mulWad(self.price);
    if (positionValueAbs <= _MIN_PARTIAL_LIQUIDATE_POSITION_VALUE) {
        return self.positionSize;
    }
}
```
The comment indicates that if the `position size` is below a predefined value, the user should liquidate the entire `position`, regardless of whether the `account value` remains above half of the `maintenance margin requirement`, in order to prevent tiny `positions` left in the system.
However, liquidators can liquidate any amount between half and the entire `position`.
## Vulnerability Detail
The `getLiquidatablePositionSize ` function returns half of the `position size` if the `account value` is above half of the `maintenance margin requirement`.
Otherwise, it returns the entire `position size`.
```solidity
function getLiquidatablePositionSize(MaintenanceMarginProfile memory self) internal view returns (int256) {
    // No liquidatable position
    if (
        self.accountValue >= self.maintenanceMarginRequirement ||
        self.positionSize == 0 ||
        self.maintenanceMarginRequirement == 0
    ) {
        return 0;
    }

    // Liquidate the entire position if its value is small enough
    // to prevent tiny positions left in the system
    uint256 positionValueAbs = self.positionSize.abs().mulWad(self.price);
    if (positionValueAbs <= _MIN_PARTIAL_LIQUIDATE_POSITION_VALUE) {
        return self.positionSize;
    }

    // Liquidator can only take over half of position if margin ratio is ≥ half of mmRatio.
    // If margin ratio < half of mmRatio, liquidator can take over the entire position.
    if (self.accountValue < self.maintenanceMarginRequirement / 2) {
        return self.positionSize;
    }
    return self.positionSize / 2;
}
```
Also the `liquidator` can request the liquidatable `position size`, and we select the minimum value.
This allows `liquidators` to liquidate any amount up to the entire `position size` when the `getLiquidatablePositionSize ` function returns the entire `position size`.
```solidity
function getLiquidatedPositionSizeDelta(
    MaintenanceMarginProfile memory self,
    uint256 sizeRequestedFromLiquidator
) internal view returns (uint256) {
    // if liquidator request to liquidate more than liquidatable size, liquidate all liquidatable size
    uint256 liquidatableSizeAbs = self.getLiquidatablePositionSize().abs();
    if (sizeRequestedFromLiquidator >= liquidatableSizeAbs) {
        return liquidatableSizeAbs;
    }

    // if liquidatable size is larger than what liquidator requested, liquidate what liquidator requested
    return sizeRequestedFromLiquidator;
}
```
## Impact
As a result, we can not prevent tiny size `positions` from remaining in the system, which also violates the documentation.
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L103-L106
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L91-L114
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L117-L129
## Tool used

Manual Review

## Recommendation
Restrict `liquidators` from being able to liquidate any amount between half and the entire `position size`.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Low - liquidator bots have the incentive to always liquidate the maximum position amount

**Comment by nevillehuang** [comment]
Invalid, I see no issue here, logic seems to be correct and aligned with documentation

**Comment by vinta** [comment]
I suppose this is invalid.

It's expected that liquidators have the incentive to always liquidate the maximum position amount. However, there're also some cases that liquidators might only want to liquidate partial positions based on their own risk management, for instance, the position size is too large, the slippage of dumping the position is high, or the liquidator simply doesn't have enough margin to take over the entire position.
