### ISSUE TITLE
ihavebigmuscle - Relay Fee is Collected All at Once, Allowing Relayers to Earn Relay Fees by Only Partially Filling Orders

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#110]
ihavebigmuscle

high

# Relay Fee is Collected All at Once, Allowing Relayers to Earn Relay Fees by Only Partially Filling Orders

## Summary
Relay Fee is Collected All at Once, Allowing Relayers to Earn Relay Fees by Only Partially Filling Orders

## Vulnerability Detail
In `OrderGatewayV2`, a relayer can only collect a relay fee from the same order key once, regardless of the amount of the order that is fulfilled, and can collect all the fees at once.

## Impact
This gives relayers the incentive to use extremely small orders, whether their own or someone else's, to match a trader's order, thereby earning relay fees in a virtually risk-free way. This can simultaneously cause losses for traders because they would need to use a new order and additional relay fees to get the remaining portion of their order filled.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/orderGatewayV2/OrderGatewayV2.sol#L303-L310

## Tool used

Manual Review

## Recommendation
It is recommended that relay fees should be collected based on the proportion of the order that has been fulfilled, rather than collecting all fees at once.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  it seem to be still one per order.

**Comment by nevillehuang** [comment]
Invalid, relayers are trusted admins as noted in contest details:

> 1. Relayer
> 2. Relayer is a permissioned address controlled by us, it'll be used to help users settle their off-chain orders(limit order, market order) on chain.
