### ISSUE TITLE
jokr - Liquidators can prevent users from making their positions healthy during an unpause

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#111]
jokr

medium

# Liquidators can prevent users from making their positions healthy during an unpause

## Summary

The Perpetual protocol admins can pause the whole system or a specific market on emergency situations . The protocol operations can be unpaused by privileged accounts. But when this unpause happens the liquidators can frontrun and liquidate user positions before those users get a chance to make their positions healthy.

## Vulnerability Detail

The Admin of the protocol can pause the whole system the using the `suspendSystem()` function in `SystemStatus` contract. Once the protocol is paused all users cannot add margin even if their positions are becoming unhealthy and liquidations are also passed.

Though, real prices from oracles will surely move up or down during this paused period. If the oracle prices go down, the users won't be allowed to add more margin or close their positions. Hence their positions will get unhealthy (based upon real prices).

Once the protocol is unpaused the liquidators can front-run most users and liquidate their positions. Most users will not get a chance to make their position healthy.

This results in loss of funds for the users.

Ref: https://github.com/sherlock-audit/2023-03-notional-judging/issues/203

## Impact
By front-running any margin deposit  or position closure of a legitimate user which became unhealthy during the paused state, the liquidator can unfairly liquidate user positions and collect liquidation profit as soon as the protocol is unpaused. This causes loss of funds to the user.

Also, on unpause, it is unlikely that any human users will be able to secure their positions before MEV/liquidation bots capture the available profit. Hence the loss is certain.

## Code Snippet

[SystemStatus.sol#L39-L43](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/systemStatus/SystemStatus.sol#L39-L43)

[Vault.sol#L93-L100](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L93-L100)

## Tool used
Manual Review

## Recommendation
Consider adding a grace period after unpausing during which liquidation remains blocked to allow users to avoid unfair liquidation by closing their positions or allocating additional collateral. The protocol team can also think of any other way which mitigates the unfair liquidations of users.

Duplicate of #59

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  this is invalid according to sherlock rules "An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue."
