### ISSUE TITLE
Kose - Unfair Liquidation After System Suspension Lift Because of Lack of Grace Period for Traders

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#139]
Kose

medium

# Unfair Liquidation After System Suspension Lift Because of Lack of Grace Period for Traders

## Summary
Suspension's in market can leads to unfair liquidations for traders without a chance for them to correct their position.
## Vulnerability Detail
Market's can be suspended by admin also it is possible to suspend the System which suspend all markets. In this period core functions won't work hence it wont be possible to deposit/withdraw, open/close position, transfer between margin and fund and also liquidate someone. Because all these functions have either modifier:
```solidity
    modifier marketExistsAndActive(uint256 marketId) {
        if (getAddressManager().getConfig().getPriceFeedId(marketId) == 0x0) revert LibError.InvalidMarket(marketId);
        _getSystemStatus().requireMarketActive(marketId);
        _;
    }
```
Or directly checks if system is active:
```solidity
    function deposit(address trader, uint256 amountXCD) external nonZero(amountXCD) nonReentrant {
        _getSystemStatus().requireSystemActive();
```

The issue arises when the suspension is lifted. Traders whose positions have lost value during the suspension period may fall below the liquidation threshold. Upon resuming normal operations, these traders are immediately vulnerable to liquidation by bots, without any opportunity to transfer additional margin to their positions to avoid liquidation.

As a result, traders face unfair liquidation without the ability to repay their debts.
## Impact
Traders can be liquidated without a way to repay their debt when suspension is removed from a market or from the system.
## Code Snippet
[SystemStatus.resumeMarket(https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/systemStatus/SystemStatus.sol/#L54)
## Tool used

Manual Review

## Recommendation
There can be multiple solutions to this. It is important to provide a grace period for traders to repay their negative PnL after suspension is removed. Suspension removal process can be recreated with two phase. In the first phase only deposits and transferFundToMargin can be callable so that traders can provide extra collateral to hold their position liquid. In the second phase all other functionalities can be opened. Or only liquidation calls may be prevented for some time after suspension is removed. But this can create further issues such that traders that are aware of this can use it to open highly leveraged positions. If the latter solution is adopted, measures to mitigate potential issues arising from it should be implemented.

Duplicate of #59

**Comment by sherlock-admin2** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid following Sherlock rules because admin is TRUSTED.

**takarez** commented:
>  according to sherlock rules; "An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue".
