### ISSUE TITLE
cats - Any user can grief the Pyth Oracle's contract balance

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#18]
cats

medium

# Any user can grief the Pyth Oracle's contract balance

## Summary
The Pyth Oracle contract's balance can be griefed and used up permissionlessly.
## Vulnerability Detail
The Pyth Oracle contract can take [deposits](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L25-L26) from anyone to be stored in the contract balance and used for [updating the price feed](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L59-L63).

```solidity
    function updatePrice(bytes32 priceFeedId, bytes memory signedData) external {
        if (!priceFeedExists(priceFeedId)) revert LibError.IllegalPriceFeed(priceFeedId);

        // Assume we always update only one oracle.
        bytes[] memory pythUpdateData = new bytes[](1);
        pythUpdateData[0] = signedData;

        // Get fee amount to pay to Pyth
        uint256 fee = _pyth.getUpdateFee(pythUpdateData);
        uint256 balance = address(this).balance;
        if (balance < fee) revert LibError.OracleFeeRequired(fee);

        _pyth.updatePriceFeeds{ value: fee }(pythUpdateData);
    }
```

The issue is that since updating the price is permissionless, any funds stored by admins or honest users to be used can depleted by malicious Alice if she just repeatedly calls the function. Furthermore, Pyth will execute the function eating up the fee regardless if given data is old and update is ignored.
## Impact
Using up all stored fee funds in the oracle contract, depleting them so they're not available when it's important to update the price.
## Code Snippet
```solidity
    function updatePrice(bytes32 priceFeedId, bytes memory signedData) external {
        if (!priceFeedExists(priceFeedId)) revert LibError.IllegalPriceFeed(priceFeedId);

        // Assume we always update only one oracle.
        bytes[] memory pythUpdateData = new bytes[](1);
        pythUpdateData[0] = signedData;

        // Get fee amount to pay to Pyth
        uint256 fee = _pyth.getUpdateFee(pythUpdateData);
        uint256 balance = address(this).balance;
        if (balance < fee) revert LibError.OracleFeeRequired(fee);

        _pyth.updatePriceFeeds{ value: fee }(pythUpdateData);
    }
```
## Tool used
Manual Review

## Recommendation
Implement a cooldown period for a user to be unable to call it repeatedly or add access control and allow only an admin bot to update it once `x` amount of time.

Duplicate of #70

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  but its expected to accurately provide data.
