### ISSUE TITLE
joicygiore - `Config:setMaxRelayFee()` uses wrong value to trigger event `emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee)`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#19]
joicygiore

medium

# `Config:setMaxRelayFee()` uses wrong value to trigger event `emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee)`

## Summary
`Config:setMaxRelayFee()` uses wrong value to trigger event `emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee)`
## Vulnerability Detail
`Config:setMaxRelayFee()` obtained the wrong `oldMaxRelayFee` value and used the wrong value to trigger the event `emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee)`
```js
    function setMaxRelayFee(uint256 maxRelayFee) external onlyOwner {
@>      uint256 oldMaxRelayFee = maxRelayFee;
        _getConfigStorage().maxRelayFee = oldMaxRelayFee;
@>      emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee);
    }
```
## Impact
`Config:setMaxRelayFee()` obtained the wrong `oldMaxRelayFee` value and used the wrong value to trigger the event `emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee)`
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/d1f68ffb481384ed604608fe25899635445d5311/perp-contract-v3/src/config/Config.sol#L100-L104
## Tool used

Manual Review

## Recommendation
```diff
    function setMaxRelayFee(uint256 maxRelayFee) external onlyOwner {
-       uint256 oldMaxRelayFee = maxRelayFee;
+       uint256 oldMaxRelayFee = _getConfigStorage().maxRelayFee;
-       _getConfigStorage().maxRelayFee = oldMaxRelayFee;
+       _getConfigStorage().maxRelayFee = maxRelayFee;
        emit MaxRelayFeeSet(maxRelayFee, oldMaxRelayFee);
    }
```

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  event emit is considered low and invalid according to sherlock rules.

**Comment by nevillehuang** [comment]
Invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 2. Incorrect Event values: Incorrectly calculated/wrong values in emitted events are not considered valid medium or high.
