### ISSUE TITLE
solmaxis69 - SpotHedgeBaseMaker.withdraw() does not check if marginRatio goes below the vault's minMarginRatio, leaving vault vulnerable to liquidation

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#22]
solmaxis69

medium

# SpotHedgeBaseMaker.withdraw() does not check if marginRatio goes below the vault's minMarginRatio, leaving vault vulnerable to liquidation

## Summary
The `minMarginRatio` check in `SpotHedgeBaseMaker` is used as a safety mechanism to ensure that the maker's marginRatio never goes below certain limit. The check is performed in `_checkMinMarginRatio()` function. As per PerpV3 docs, the SpotHedgeMaker should revert if `vaultMarginRatio < minMarginRatio` [(see here)](https://perp.notion.site/SpotHedgeMaker-5b9d196723d4471c8818fe65ad7b9ce0). However, this check is not present in the `SpotHedgeBaseMaker.withdraw()` function, leaving vault vulnerable to liquidation.
Additionally, the same check exists in `OracleMaker.withdraw()`.
## Vulnerability Detail
See summary
## Impact
Protocol invariant broken, the maker vault could be vulnerable to liquidation
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L303-L357
## Tool used

Manual Review

## Recommendation
If there are any quote tokens to withdraw, call the `_checkMinMarginRatio()` function after withdrawal:
```solidity
 if (withdrawnQuoteAmount > 0) {
            // withdrawnQuoteAmount is calculated base on freeCollateral, and since all conversions are round-down,
            // we can safely assume withdrawnQuoteAmount <= freeCollateral and the withdraw should always pass.
            // It may not be possible to withdraw the required amount, due to unsettledPnl that cannot be settled totally.
            _withdraw(vault, _getSpotHedgeBaseMakerStorage().marketId, withdrawnQuoteAmount);
            _checkMinMarginRatio(); // @audit
            _getSpotHedgeBaseMakerStorage().quoteToken.safeTransfer(lp, withdrawnQuoteAmount);
        }
```

Duplicate of #34

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid - The min margin ratio will be checked at vault.transferMarginToFund()
