### ISSUE TITLE
PUSH0 - Adversary can grief Pyth oracle adapter's fees by spamming updates in the past

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#28]
PUSH0

medium

# Adversary can grief Pyth oracle adapter's fees by spamming updates in the past

## Summary

When a past (stale) price update is pushed onto the Pyth oracle using `IPyth.updatePriceFeeds()`, the update is ignored.

However the catch is that excess fees are not returned. Anyone can then grief the adapter's fees by spamming price update from the past.

## Vulnerability Detail

Quoting the [Pyth docs](https://docs.pyth.network/price-feeds/pythnet-price-feeds/pull-updates):

> On-chain prices can only move forward in time. If a user submits a Wormhole message with a less recent price the Pyth program will not fail but will also not update the price. 

Therefore, redundant updates (e.g. updates in the past) will get ignored, but the tx will not revert.

However, the adapter currently uses Pyth function `updatePriceFeeds()`, which does not return excess fees on update:

https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/ethereum/contracts/contracts/pyth/Pyth.sol#L71-L95

Therefore anyone can grief Perp's deposited Oracle adapter fees by spamming an update in the past through `updatePrice()`.

## Impact

Fees will be eaten up on past price updates, opening up room for griefing.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L51

## Tool used

Manual review

## Recommendation

Pyth provides a contract method to do push strictly fresh updates only, that is `updatePriceFeedsIfNecessary()`. With the same parameters signature, it also reverts upon a stale update. We recommended to use this method instead of `updatePriceFeeds()`.
- Alternatively, the adapter can also perform a price read after the update, and check if the updated timestamp is sufficiently fresh. This additionally prevents the spam technique with newer but already stale prices (e.g. spamming updates 30 minutes ago, increasing by the second).

Duplicate of #70

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  its trusted to provide accurate data
