### ISSUE TITLE
PUSH0 - No slippage check for deposit/withdraw in either Makers

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#29]
PUSH0

high

# No slippage check for deposit/withdraw in either Makers

## Summary

There is no slippage check in either depositing or withdrawing in either of the Makers.

Unlike a regular ERC4626, share exchange rates in Makers are not uponly, and is dependent on trades happening. Thus the exchange rate can be highly volatile, and it is possible that LPs will incur loss through slippage when deposit or withdraw.

## Vulnerability Detail

In both `OracleMaker` and `SpotHedgeBaseMaker`, there are no slippage control in either deposit or withdraw:
- Deposit does not check for minimum expected shares out.
- Withdraw does not check for minimum expected assets out.

OracleMaker:

```solidity
function deposit(uint256 amountXCD) external onlyWhitelistLp returns (uint256) { // no MinSharesOut
```

```solidity
function withdraw(uint256 shares) external onlyWhitelistLp returns (uint256) { // no minAmountOut
```

SpotHedgeBasedMaker:

```solidity
function deposit(uint256 amountXBD) external onlyWhitelistLp returns (uint256) { // no MinSharesOut
```

```solidity
function withdraw(uint256 shares) external onlyWhitelistLp returns (uint256) { // no minAmountOut or similar
```

In a regular ERC4626 setting, the 4626 vault exchange rate is uponly, therefore LPs cannot incur losses due to slippage.

However, since the share value of a Maker is calculated by its account value, which is the sum of their margin and PnL, the share value is not uponly but is highly volatile, and thus a loss through slippage will likely happen.

A scenario in which slippage can happen for a withdraw is as follow:
- LP wants to deposit or withdraw assets.
- A regular trader updates the Pyth price to perform a regular operation, inadvertently changing the Maker's vault value. 
  - Any action that updates a Pyth price feed applies here, since the Maker's exchange rate is dependent on it. 
- LP's transaction goes through. However their actual assets/shares received is much less than expected, due to the changing account value of the maker.

The inverse situation can also happen with a deposit. A trader can cut their losses and creates profit for the vault, lessening the number of shares the LP receives.

This scenario can happen even without front-running purely by coincidence, especially during an active market. This is why AMMs must still implement slippage control, even on chains without a public mempool, as this kind of loss can occur if there is a sudden price movement, especially in volatile assets.

## Impact

Due to slippage created by price movements that is completely not in the LP's control:
- For a deposit, LPs can receive much less shares than they expect.
- For a withdraw, LPs can receive much less assets than they expect.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L175

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L228

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L255

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L303

## Tool used

Manual review

## Recommendation

Implement a slippage check for both deposit and withdraw in each Maker.
- For `SpotHedgeBaseMaker`'s withdraw, it may be more difficult on how to evaluate assets out. One way is to check the sum of assets out's amount on the Oracle price.

Duplicate of #121

**Comment by sherlock-admin2** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  there is no need of slippage here as there's nothing sort of a swapping going on.
