### ISSUE TITLE
0xRobocop - Pyth Oracle Latency Protection is not applied to Makers Vaults

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#30]
0xRobocop

medium

# Pyth Oracle Latency Protection is not applied to Makers Vaults

## Summary

Users can take advantage of the pyth oracle latency to sandwich them with the deposit / withdraw operations in the Oracle Maker contract.

## Vulnerability Detail

The price is an important variable to compute the position's value of the Oracle Maker contract, which is used to compute the share price for deposits and withdraws.

Pyth oracles' price changes can be known before they are submitted on-chain. To protect the OracleMaker vault from this, orders must go through orderGatewayV2, which only settles the orders via trusted relayers. This prevents attackers from taking advantage of the Pyth oracle latency.

The issue is that the same protection is not applied to the deposit and withdraw functions of the Oracle Maker contract, which allows malicious users to sandwich the oracle price changes to dilute the profit of legit depositors. For example:

State before oracle price change:

- `shares = 1000`
- `vaultValue = 1000` (assume maker is long  with a position size of 1000 and open notional of 1000 (price of 1).

Pyth oracle will change to 1.1 quote / base, and before this update the attacker deposits into the Vault 10_000 collateral tokens minting 10_000 shares.

After the price change the state is the following:

- `shares = 11_000`
- `vaultValue = 11_100` (100 profit from the price change).

The attacker can now withdraw 10_090 tokens stealing 90% of the profit.

## Impact

Malicious user can steal profits from legit depositors.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L189

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L241
## Tool used

Manual Review

## Recommendation

Apply a delay on the execution of deposits and withdrawals.

Duplicate of #121

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid - Not possible to sandwich oracle updates because there's no MEV on L2s
