### ISSUE TITLE
nuthan2x - Markets with `pythPrice.expo > 0` cannot be processed by perpetual system

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#33]
nuthan2x

medium

# Markets with `pythPrice.expo > 0` cannot be processed by perpetual system

## Summary
Markets with `pythPrice.expo > 0` cannot be integrated to perpetual system and if pyth decides to change the expo to positive value anytime for the current pricefeeds reporting ve expo values, new orders cannot be replayed and liquidations can fail, because price fetch handling will revert.

## Vulnerability Detail

```solidity
    function _convertToUint256(PythStructs.Price memory pythPrice) internal pure returns (uint256) {
        // Remember to update the conversion formula below accordingly if you have changed the conditions.
        // Note both calculations below rely on the conditions here to prevent from overflow.
        // Be sure to double check if you change the conditions.
🟥     if (pythPrice.price < 0 || pythPrice.expo > 0 || pythPrice.expo < -int8(INTERNAL_DECIMALS)) 
            revert IllegalPrice(pythPrice);

        // .price = 181803
        // .expo = -2
        // decimal price = 181803 * 10^(-2) =  1818.03
        // converted price = 181803 * 10^(18 - 2) = 1.81803e21

        uint256 baseConversion = 10 ** uint256(int256(int8(INTERNAL_DECIMALS)) + pythPrice.expo);

        return uint256(int256(pythPrice.price)) * baseConversion;
    }
```
The pyth prices return price with `expo` param to handle the decimals. But perpetual team validates here to be  < 0  always, but pyth can return in +ve  values > 0 too. And the check `pythPrice.expo < 0` is there to prevent underflow on casting. But expo being > 0 will never make it overflow on casting.

Adding more proof that expo can be > 0  on some feeds, or even  > 0 on current feeds because the rust code of their backend allows it to, so updte by their signature based backend can impact the curren tfeeds that change from  < 0 into > 0.

1. discord chat by their devs ==> https://discord.com/channels/826115122799837205/842994700864192562/1181623548989673482

![image-2](https://github.com/sherlock-audit/2024-02-perpetual-nuthan2x/assets/92864243/806e540c-7dca-4233-af37-fcbfe7afc9a7)

2. chat 2 ==> https://discord.com/channels/826115122799837205/842994700864192562/1181664192177115177

![image-3](https://github.com/sherlock-audit/2024-02-perpetual-nuthan2x/assets/92864243/f09556dc-93a2-46cd-bb8f-f1edb7a73c44)

3. pyth rust backend ==> 
    - https://github.com/pyth-network/pyth-client/blob/3f10185d2dbf81a27be1fcf89f0c187bb6a5ec0f/program/rust/src/utils.rs#L120-L123
    - https://github.com/pyth-network/pyth-client/blob/3f10185d2dbf81a27be1fcf89f0c187bb6a5ec0f/program/rust/src/c_oracle_header.rs#L14
    
4. Previous issue on other contest handling pyth oracle, showing the mis handling of the expo parameter

https://github.com/sherlock-audit/2023-07-perennial-judging/issues/45

5. Cap.io perp dex handling ==> https://arbiscan.io/address/0xf7D5E17b430bF1e8B55B3675E5c216e6Abc4fA39#code#F16#L422

![image-4](https://github.com/sherlock-audit/2024-02-perpetual-nuthan2x/assets/92864243/f09644fb-b3cc-4935-b561-1b802008cc6c)

## Impact
Markets with `pythPrice.expo > 0` cannot be integrated to perpetual system and if pyth decides to change the expo to positive value anytime for the current pricefeeds reporting ve expo values, new orders cannot be replayed and liquidations can fail, because price fetch handling will revert.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L103

## Tool used

Manual Review

## Recommendation

Remove the positive expo value validation.

```diff
    function _convertToUint256(PythStructs.Price memory pythPrice) internal pure returns (uint256) {
        // Remember to update the conversion formula below accordingly if you have changed the conditions.
        // Note both calculations below rely on the conditions here to prevent from overflow.
        // Be sure to double check if you change the conditions.
-       if (pythPrice.price < 0 || pythPrice.expo > 0 || pythPrice.expo < -int8(INTERNAL_DECIMALS)) 
+       if (pythPrice.price < 0 || pythPrice.expo < -int8(INTERNAL_DECIMALS)) 
            revert IllegalPrice(pythPrice);

        // .price = 181803
        // .expo = -2
        // decimal price = 181803 * 10^(-2) =  1818.03
        // converted price = 181803 * 10^(18 - 2) = 1.81803e21

        uint256 baseConversion = 10 ** uint256(int256(int8(INTERNAL_DECIMALS)) + pythPrice.expo);

        return uint256(int256(pythPrice.price)) * baseConversion;
    }
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  but its expected to provide an accurate data according to the readMe.

**Comment by nevillehuang** [comment]
Invalid, both USDT and USDC pyth oracles utilizes negative exponents
