### ISSUE TITLE
zraxx - Function `sync` incorrectly sets limiter’s listHead, which delays the next clearing of the linked list.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#37]
zraxx

medium

# Function `sync` incorrectly sets limiter’s listHead, which delays the next clearing of the linked list.

## Summary

Function `sync` incorrectly sets limiter’s listHead, which delays the next clearing of the linked list.

## Vulnerability Detail

In function `sync`, when the limiter‘s listNodes are empty after clearing (which means listHead equals to 0), the limiter‘s will be change to the block.timestamp instead of currentTickTimestamp. Since block.timestamp is greater than or equal to currentTickTimestamp, the next clearing operation will be delayed. 

The most obvious manifestation is that if the function `sync` is triggered in the function `recordChange`, two nodes will be added to the listNode, namely currentTickTimestamp and block.timestamp. At this time, since the first node is block.timestamp (amount=0) and the second node is currentTickTimestamp, the clearing of the second node will be delayed.

## Impact

The clearing to list nodes will be delayed.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/circuitBreaker/LibLimiter.sol#L106

## Tool used

Manual Review

## Recommendation

```solidity
limiter.listHead = currentTickTimestamp;
limiter.listTail = currentTickTimestamp;
```

**Comment by nevillehuang** [comment]
Invalid, known issue

> 11. In CircuitBreaker LibLimiter, limiter.listHead/listTail no initially set to currentTickTimestamp
