### ISSUE TITLE
0x73696d616f - Confidence interval of Pyth oracle should be used to protect the protocol from volatility and uncertainty

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#39]
0x73696d616f

medium

# Confidence interval of Pyth oracle should be used to protect the protocol from volatility and uncertainty

## Summary
Pyth prices fetched using `getPriceNoOlderThan()` have a confidence parameter that is ignored at the moment; however, it should be used to measure the realiability of the price and take preventive measures.

## Vulnerability Detail
In the Pyth Oracle [documentation](https://docs.pyth.network/price-feeds/pythnet-price-feeds/best-practices), it can be seen that the confidence interval should be used to protect the protocol against market uncertainty. This confidence interval is a measure of the likelihood of the published price being closed to the actual price. A brief explanation is given in the docs, namely:
Publishers publish a price and a confidence interval. From these values, its possible to get a price interval, `(μ-σ, μ+σ)`, where `μ` represents the aggregate price and `σ` represents the aggregate confidence.

## Impact
Inaccurate prices leading to sudden losses or profits that could significantly impact the protocol in times of higher volatility.

## Code Snippet
[`getPrice()`](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L80).
```solidity
function getPrice(bytes32 priceFeedId) public view returns (uint256, uint256) {
    // We don't use pyth.getPrice(), so we can control when to revert with _maxPriceAge,
    // reverted with StalePrice if price.publishTime exceeds _maxPriceAge
    try _pyth.getPriceNoOlderThan(priceFeedId, _maxPriceAge) returns (PythStructs.Price memory price) {
        // Assumes base price is against quote
        return (_convertToUint256(price), price.publishTime);
    } catch (bytes memory reason) {
        revert LibError.OracleDataRequired(priceFeedId, reason);
    }
}
```

## Tool used
Vscode
Manual Review

## Recommendation
Using the price interval mentioned in the Vulnerability Detail section, the following measures should be implemented:
1. Opening, closing positions and liquidations should choose the worst price for the trader, such that the protocol is protected and bad debt is limited. In the documentation they give the example that when a user supplies some collateral, its value should be the lower price, `μ-σ`. When evaluating a loan, it should use the upper interval `μ+σ`.
2. Pausing the protocol for prices that have a bad confidence interval, defined by `σ/μ`.
Alternatively, the moving average price, or `getEmaPriceNoOlderThan()`, could be used instead.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  its expected to provide accurate data

**Comment by nevillehuang** [comment]
Invalid, this would fall under the following category relating to accuracy of market prices

> Oracle (Pyth) is expected to accurately report the price of market
