### ISSUE TITLE
0xumarkhatab - Whitelisted users can never be liquidated in the long term even if protocol intends it in short term

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#44]
0xumarkhatab

medium

# Whitelisted users can never be liquidated in the long term even if protocol intends it in short term

## Summary
Protocol intends to add the functionality of liquidation of whitelisted users but due to non-upgradability and in-flexible logic ,
the system won't be able to incorporate new changes 
## Vulnerability Detail
Inside `ClearingHouse.sol` , the function `liqudate` aims to liquidate users based on whether user has healthy collateral or not.

```solidity

   function liquidate(
        LiquidatePositionParams calldata params
    ) external nonZero(params.positionSize) returns (int256, int256) {
        // We don't allow liquidating whitelisted makers for now until we implement safety mechanism
        // For spot-hedged base maker, it needs to implement rebalance once it got liquidated
        if (_isWhitelistedMaker(params.marketId, params.trader)) {
            revert LibError.CannotLiquidateWhitelistedMaker();
        }

        // calculate how much size can be liquidated, and how much open notional will be reduced correspondingly
        address liquidator = _sender();
        MaintenanceMarginProfile memory mmProfile = _getMaintenanceMarginProfile(
            params.marketId,
            params.trader,
            _getPrice(params.marketId)
        );
        LiquidationResult memory result = mmProfile.getLiquidationResult(params.positionSize);
        if (result.liquidatedPositionSizeDelta == 0) revert LibError.NotLiquidatable(params.marketId, params.trader);

        // settle to vault, pay out liquidation fee to liquidator and protocol
        IVault vault = _getVault();
        int256 liquidatorPositionSizeBefore = vault.getPositionSize(params.marketId, liquidator);
        vault.settlePosition(
            IVault.SettlePositionParams({
                marketId: params.marketId,
                taker: params.trader,
                maker: liquidator,
                takerPositionSize: result.liquidatedPositionSizeDelta,
                takerOpenNotional: result.liquidatedPositionNotionalDelta,
                reason: PositionChangedReason.Liquidate
            })
        );
        vault.transferMargin(params.marketId, params.trader, liquidator, result.feeToLiquidator);
        vault.transferMargin(params.marketId, params.trader, address(this), result.feeToProtocol);

        // always check margin in the end
        _checkMarginRequirement(
            CheckMarginRequirementParams({
                vault: vault,
                marketId: params.marketId,
                trader: liquidator,
                price: mmProfile.price,
                isReducing: LibPosition.isReduceOnly(
                    liquidatorPositionSizeBefore,
                    vault.getPositionSize(params.marketId, liquidator)
                )
            })
        );
        _emitLiquidatedEvent(
            EmitLiquidatedEventParams({
                marketId: params.marketId,
                liquidator: liquidator,
                trader: params.trader,
                positionSizeDelta: result.liquidatedPositionSizeDelta,
                positionNotionalDelta: result.liquidatedPositionNotionalDelta,
                price: mmProfile.price,
                penalty: result.penalty,
                liquidationFeeToLiquidator: result.feeToLiquidator,
                liquidationFeeToProtocol: result.feeToProtocol
            })
        );
        return (result.liquidatedPositionSizeDelta, result.liquidatedPositionNotionalDelta);
    }
```
However , this function does not allow the liquidation of whitelisted users.
See following first require statement

```solidity
 if (_isWhitelistedMaker(params.marketId, params.trader)) {
            revert LibError.CannotLiquidateWhitelistedMaker();
        }
```
If the trader is a whitelisted User, it will always revert , preventing the liquidation of the user.
When we look closely just above this require check , there's a comment

```solidity
 // We don't allow liquidating whitelisted makers for now until we implement a safety mechanism
        
```
This tells us that protocol does not always want to prevent the liquidation of whitelisted users. 

In the Future, the protocol wants to add some mechanism to liquidate whitelisted users safely too.

However, in the current implementation, we don't see methods like the following to enable this feature in future

- Some Boolean value state variables like `isWhitelistedLiquidationEnabled` that can be toggled on or off ( initially it will be off for the current version ) to decide in the require statement whether to liquidate the whitelisted user or not.
- The ClearingHouse Contract is not upgradable. Being the contract upgradable gives us the chance to add new functions and variables reliably. However, the lack of this pattern deems the protocol to never be able to add whitelisted user's liquidation.

## Impact
Whitelisted users will never be liquidated.
So whitelisted users can do huge amounts of trades even if their health factor is not ok. 
If one of the Whitelisted users becomes malicious, knowing they will never be liquidated , they can do malicious things that 
can cause loss of funds for either users or protocol

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L161-L168

## Tool used

Manual Review

## Recommendation

There are two ways to make ClearingHouse future-ready and robust.

1. Make ClearingHouse Upgradable
2. The reliable method is to add a state variable `isWhitelistedLiquidationEnabled`, add an only owner setter for this variable, and then modify the liquidation condition as follows

```solidity
 if ( !isWhitelistedLiquidationEnabled && _isWhitelistedMaker(params.marketId, params.trader)) {
            revert LibError.CannotLiquidateWhitelistedMaker();
        }
```

Duplicate of #140

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  a safer mechanisms will be implemented as per code comments before allowing liquidationo whitelisted makers(natsepc).
