### ISSUE TITLE
0xumarkhatab - DoS : quoteOpenPosition will always fail

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#47]
0xumarkhatab

high

# DoS : quoteOpenPosition will always fail

## Summary
Due to a plain revert statement in `quoteOpenPosition ` , the function will always revert no matter what.

## Vulnerability Detail

The function definition of `quoteOpenPosition ` is as follows :

```solidity
    function quoteOpenPosition(OpenPositionParams calldata params) external returns (int256, int256) {
        address taker = _sender();
        uint256 price = _getPrice(params.marketId);

        IVault vault = _getVault();
        OpenPositionResult memory result = _openPosition(vault, taker, params, PositionChangedReason.Trade);

        // Only check maker's margin is sufficient for filling order
        _checkMarginRequirement(
            CheckMarginRequirementParams({
                vault: vault,
                marketId: params.marketId,
                trader: params.maker,
                price: price,
                isReducing: result.isMakerReducing
            })
        );

        revert LibError.QuoteResult(result.base, result.quote);
    }

```
The last line is interesting.
No matter how well the upper portion of the function is executed.
This function will always revert due to following line 

```solidity
        revert LibError.QuoteResult(result.base, result.quote);

```
Carefully check that this line does not have any if-branching to revert in some cases and not in others.
As function is `external` and protocol intends users to call it more often , when the they face the denial of service in quoting an open position , the impact is high.
Clearly the likelihood is high
so High severity is appropriate.

## Impact
DoS in QuoteOpenPosition for users
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L117-L136
## Tool used

Manual Review

## Recommendation
Remove the non-conditional revert

**Comment by nevillehuang** [comment]
Invalid, expected to revert as noted by comments [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/quoter/Quoter.sol#L23)
