### ISSUE TITLE
enfrasico - `getDepositCap()` will continually incidentally be decreased overtime on Blast

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#49]
enfrasico

medium

# `getDepositCap()` will continually incidentally be decreased overtime on Blast

## Summary
Based on the protocol provided context, perpetual is intended to be deployed on Optimism/Blast.

`getDepositCap()` is used to set a cap for maximum amount of collateral a vault can accept. Protocol supports USDC/USDT as collateral and they are minted as USDB on Blast. However, because native USDB on Blast is rebasing, `getDepositCap()`, while a fixed value, the effective cap will continually decrease over time.

## Vulnerability Detail

`_checkDepositCap()` checks for balance of in vault address of collateral token to determine the current amount of deposits. However, this value is inaccurate due to USDB's native rebasing feature. When USDB is used as collateral, it will continue to rebase up. This will continually increase balance of the vault contract overtime. Protocol's intended deposit cap will be lesser than what is set. 

```javascript
function _checkDepositCap() internal view {
    uint256 depositCap = _getConfig().getDepositCap();
    if (IERC20Metadata(_getVaultStorage().collateralToken).balanceOf(address(this)) > depositCap) {
        revert LibError.DepositCapExceeded();
    }   
}
```

## Impact
Protocol's actual deposit cap will be lesser than what is being set. While in theory, protocol can change deposit cap to a high value to compensate for amount that has been accrued, this is only a temporary solution. `USDB.balanceOf()` will continue to increase in the vault for perpetuaity, and protocol has to constantly increase the deposit cap.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L480-L485

## Tool used

Manual Review

## Recommendation
Implement a way to set yield mode on vault contract to CLAIMABLE, so that deposit cap is a fixed value.

**Comment by nevillehuang** [comment]
Invalid, as mentioned by watson deposit caps can always be adjusted accordingly as seen [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/config/Config.sol#L180-L184) and should be taken account by admin adjusting values
