### ISSUE TITLE
enfrasico - USDC/USDT yield accrued in vaults cannot be claimed on Blast

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#51]
enfrasico

high

# USDC/USDT yield accrued in vaults cannot be claimed on Blast

## Summary 
Based on the protocol provided context, perpetual is intended to be deployed on Optimism/Blast.

Perpetual protocol allows users to deposit USDC/USDT into vaults. These funds will sit in the vault contract. On Blast, USDC/USDT that are bridged from ETH are automatically converted to USDB. USDB is a native rebasing token representing USDC/USDT/DAI. USDB has different yield mode contracts can set. The default yield mode is AUTOMATIC. The yields accrued in the vault will be stuck in the contract as there is no way to claim them.

## Vulnerability Detail
Vault contract uses internal accounting to account for how much collateral users has deposited into the vault. For instance, when `deposit()` is called, deposited amount is tracked via `_updateFund()`. These funds deposited into the vault will continue to accrue yield, which should belong to the protocol. However, due to lacking ways to claim them, the yield will be lost forever in the contract.

Rating this as high severity as vault is meant to hold a large amount of USDC/USDT deposited by users, hence accrued yield loss for protocol is massive.

## Impact
Massive loss of USDB yield for protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L93-L99

## Tool used

Manual Review

## Recommendation
Implement a way for protocol to withdraw USDB that has been accrued which are not user funds.

Duplicate of #50

**Comment by Coareal** [comment]
Escalate

This issue is incorrectly duped to #50. The judge should not confuse all Blast related issues as the same one.

Protocol deploys the Vault on Blast. USDC/USDT on Blast AUTOMATICALLY accrues yield similar to rebasing tokens such as stETH on ETH mainnet.

If we have 10 million USDC/USDT in the contract, a year later contract would hold 11.5 million USDC/USDT(current yield is 15%). The protocol does not have anyway to claim the accrued 1.5 million yield. This is a very clear high issue and is in no way the same as an airdrop as commented by the judge on #50.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is incorrectly duped to #50. The judge should not confuse all Blast related issues as the same one.
> 
> Protocol deploys the Vault on Blast. USDC/USDT on Blast AUTOMATICALLY accrues yield similar to rebasing tokens such as stETH on ETH mainnet.
> 
> If we have 10 million USDC/USDT in the contract, a year later contract would hold 11.5 million USDC/USDT(current yield is 15%). The protocol does not have anyway to claim the accrued 1.5 million yield. This is a very clear high issue and is in no way the same as an airdrop as commented by the judge on #50. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I believe head of judging opinion supports my stance as seen [here](https://discord.com/channels/812037309376495636/1013592891773419520/1225758233625366569). I believe one reason for not including yield claim could be bytecode limit.

**Comment by Coareal** [comment]
> I believe head of judging opinion supports my stance as seen [here](https://discord.com/channels/812037309376495636/1013592891773419520/1225758233625366569). I believe one reason for not including yield claim could be bytecode limit.

Respectfully, I'm sorry but that is one insane claim to make. Are you saying that protocols are willing to forgo 15% annual yield on principal TVL because of "bytecode limit"?

I would also love to hear head of judging's reasoning for comparing **NATIVE** rebasing token yield to airdrops.

**Comment by Czar102** [comment]
Yield that is not a part of the protocol design is considered to be like an airdrop, and hence this is correctly judged as informational. Planning to reject the escalation and leave the issue as is.

**Comment by Coareal** [comment]
You cannot claim yield to be "not part of the protocol design", when a protocol is deployed on Blast and USDC is used.

USDC is a rebasing token on Blast and comparing it to an "airdrop" which is usually of another token is simply incorrect. This is equivalent to calling stETH's native yield to be an "airdrop".

**Comment by WangSecurity** [comment]
Agree with the points by Czar above. Moreover, I believe it's an opportunity loss and no core functionality is broken here. Planning to reject the escalation and leave the issue as it is.

**Comment by Coareal** [comment]
Hi @WangSecurity 

I would appreciate if the points I have made is responded to. Thank you.

> If we have 10 million USDC/USDT in the contract, a year later contract would hold 11.5 million USDC/USDT(current yield is 15%). The protocol does not have anyway to claim the accrued 1.5 million yield.

> USDC is a rebasing token on Blast and comparing it to an "airdrop" which is usually of another token is simply incorrect. This is equivalent to calling stETH's native yield to be an "airdrop".

**Comment by WangSecurity** [comment]
Unfortunately, this points don't change the fact that it's an opportunity loss and no core functionality of perpetual protocol is broken.

**Comment by Coareal** [comment]
This issue is a definitive loss of funds, not just an "opportunity loss". There is no arguing against this.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #50

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/51/#issuecomment-2040801392): rejected

**Comment by Evert0x** [comment]
Agree with the judgment of @WangSecurity
