### ISSUE TITLE
enfrasico - Circuit breaker and oracle adapter is not able to accrue native ETH yield on Blast

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#52]
enfrasico

medium

# Circuit breaker and oracle adapter is not able to accrue native ETH yield on Blast

## Summary
Based on the protocol provided context, perpetual is intended to be deployed on Optimism/Blast. 

Blast is a yield based L2 chain that allows native ETH to be rebasing. Native ETH held in both the circuit breaker and oracle adapter contracts cannot accrue yield since default yield mode of native ETH on Blast is VOID.

## Vulnerability Detail
It is clear from the implementation that the circuit breaker contract is meant to support both ERC20 tokens and native tokens. We see implementations such as `onNativeAssetOutflow()` and `_safeTransferIncludingNative()` which can transfer ETH from the contract.

Oracle adapter holds native ETH in order to pay for oracle fee. 

Both of these contracts do not have a way to set native ETH yield mode. As a result, no yields are accrued for native ETH residing in these contracts.

## Impact
Loss of ETH yield for protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L25
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/circuitBreaker/CircuitBreaker.sol#L129-L134

## Tool used

Manual Review

## Recommendation
Implement a way for protocol to set yield mode for the vulnerable contracts to AUTOMATIC or CLAIMABLE.

Duplicate of #50

**Comment by Coareal** [comment]
Escalate

This issue is incorrectly duped to #50. The judge should not confuse all Blast related issues as the same one.

Protocol deploys the Vault on Blast. Default yield mode for native ETH on Blast is VOID. Protocol has to implement functions to set the native ETH yield mode to CLAIMABLE or AUTOMATIC to accrue yield. Not doing so is equivalent to losing yield. 

This should not be compared to an airdrop because this is an expected interaction when protocols are deployed on Blast, and in fact the whole purpose of Blast L2.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is incorrectly duped to #50. The judge should not confuse all Blast related issues as the same one.
> 
> Protocol deploys the Vault on Blast. Default yield mode for native ETH on Blast is VOID. Protocol has to implement functions to set the native ETH yield mode to CLAIMABLE or AUTOMATIC to accrue yield. Not doing so is equivalent to losing yield. 
> 
> This should not be compared to an airdrop because this is an expected interaction when protocols are deployed on Blast, and in fact the whole purpose of Blast L2.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I believe head of judging opinion supports my stance as seen [here](https://discord.com/channels/812037309376495636/1013592891773419520/1225758233625366569). I believe one reason for not including yield claim could be bytecode limit.

**Comment by Czar102** [comment]
This yield isn't a part of the protocol design, so this finding is invalid anyway, even though it should not be a duplicate of #50. Planning to reject the escalation.

**Comment by WangSecurity** [comment]
Agree with comments by Czar. This is an opportunity loss, no core functionality is broken here. Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #50

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/52/#issuecomment-2040802950): rejected
