### ISSUE TITLE
0xumarkhatab - SystemStatus can be bricked by making it non-operational through renounce ownership

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#53]
0xumarkhatab

medium

# SystemStatus can be bricked by making it non-operational through renounce ownership

## Summary
Renouncing ownership in SystemStatus.sol can brick it entirely pausing the core functionalities updates

## Vulnerability Detail
SystemStatus.sol has some owner only functions like follows which are responsible for critical aspects of the system.

```solidity
  function suspendSystem() external onlyOwner {
        _getSystemStatusStorage().systemSuspended = true;
        emit SystemSuspended();
    }

    function resumeSystem() external onlyOwner {
        _getSystemStatusStorage().systemSuspended = false;
        emit SystemResumed();
    }

    function suspendMarket(uint256 marketId) external onlyOwner {
        _getSystemStatusStorage().marketSuspendedMap[marketId] = true;
        emit MarketSuspended(marketId);
    }

    function resumeMarket(uint256 marketId) external onlyOwner {
        _getSystemStatusStorage().marketSuspendedMap[marketId] = false;
        emit MarketResumed(marketId);
    }
```

However, there is also a privileged function renounceOwnership that can be used by the owner to give up ownership of the contract leaving entire system to be ownerless and not being able to change any further critical params like 
suspending system ,resume & suspend Market in different scenarios to protect users and protocol.

Good security firms advise great protocols to never allow the renouncing of ownership because the effect is much larger.

Likelihood : Low
Impact : High
## Impact
Critical parameters change ike Suspending system ,resume & suspend Market in different scenarios to protect users and protocol will not be functional once ownership is given up.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/systemStatus/SystemStatus.sol#L10
## Tool used

Manual Review

## Recommendation

Override the renounceOwnership function to not include any implementation and hence not allow this action of giving up ownership

```solidity
function renounceOwnership() public  override  onlyOwner {

    }
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  invalid

**Comment by nevillehuang** [comment]
Invalid, owners are trusted not to renounce ownership arbitrarily
