### ISSUE TITLE
0xumarkhatab - Depositors who are blacklisted by USDC can not get their collateral back

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#54]
0xumarkhatab

medium

# Depositors who are blacklisted by USDC can not get their collateral back

## Summary
The withdraw function in Vault.sol sends the tokens back to the user. The Expected Tokens to use stated by protocol are usdt and usdc. The problem is if the trader is blacklisted by usdc after some time of depositing into the vault, the flow of withdraw will fail.

## Vulnerability Detail
USDC has the abilty to blacklist users.

Consider following scenario :

- User A deposits 1 Million USDC collateral in Vault using deposit function ( he is not blacklisted yet )
- After some time , USDC blacklists user A due to some actions the user A took ( Even tough User A might be innocent )
- Now User A wants to give up USDC usage and wants to withdraw his collateral from the protocol.
- The contract try to send his collateral back to user but due to him being blacklisted , the withdraw function fails to send him the tokens back.

```solidity
    function withdraw(uint256 amountXCD) external nonZero(amountXCD) nonReentrant {
        _getSystemStatus().requireSystemActive();

        address trader = _sender();
        _updateFund(trader, -amountXCD.toInt256());

        // revert if hit withdrawal rate limit
        // we don't use the lockedFund-related features in Circuit Breaker for now
        _transferCollateralOut(trader, amountXCD, true);
    }
```

## Impact
User A loses his 1 Million USDC because there is no way to add a second address that withdraw on his behalf

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L102C1-L111C6

## Tool used

Manual Review

## Recommendation
Add a mechanism for users to withdraw their holdings using another address if they want to

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  this is a self-harm and invalid according to sherlock

**Comment by nevillehuang** [comment]
Invalid based on the following sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 9. User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.
