### ISSUE TITLE
0xumarkhatab - Liquidation will fail if trader or liquidater is blacklisted by USDC

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#55]
0xumarkhatab

medium

# Liquidation will fail if trader or liquidater is blacklisted by USDC

## Summary
The liquidation function will fail if either the trader of the position or the liquidator who is liquidating the user is blacklisted by the 
## Vulnerability Detail

Case 1 : 

Take the following scenario :

- Alice deposits 1 Million USDC collateral 
- She makes some trades on Perpetual V3 that benefit her but her health factor is dropped so that she can be liquidated.
- Bob , a liquidator tries to liquidate her.
- Due to the transferring of assets , Alice's address will be involved in making the USDC transaction.
- USDC will make the transfer fail as Alice is blacklisted.
- Alice will never be liquidated
If she gets aware of it , she can creatively manipulate the system by trading large volumes because she will never have the fear of being liquidated and she can make profit

Case 2 : 

Suppose in the first scenario , if liquidator is blacklisted , Alice will not be liquidated because the liquidation involves transacting the funds to the liquidator who is blacklisted so USDC will not allow this transaction and hence the flow of liquidation will fail.

## Impact
- Alice will never get liquidated so now she can abuse this opportunity to trade more even though her collateral becomes
far below than required
- Protocol functionality assumptions will be compromised

```solidity

    function liquidate(
        LiquidatePositionParams calldata params
    ) external nonZero(params.positionSize) returns (int256, int256) {
        // We don't allow liquidating whitelisted makers for now until we implement safety mechanism
        // For spot-hedged base maker, it needs to implement rebalance once it got liquidated
        if (_isWhitelistedMaker(params.marketId, params.trader)) {
            revert LibError.CannotLiquidateWhitelistedMaker();
        }

        // calculate how much size can be liquidated, and how much open notional will be reduced correspondingly
        address liquidator = _sender();
        MaintenanceMarginProfile memory mmProfile = _getMaintenanceMarginProfile(
            params.marketId,
            params.trader,
            _getPrice(params.marketId)
        );
        LiquidationResult memory result = mmProfile.getLiquidationResult(params.positionSize);
        if (result.liquidatedPositionSizeDelta == 0) revert LibError.NotLiquidatable(params.marketId, params.trader);

        // settle to vault, pay out liquidation fee to liquidator and protocol
        IVault vault = _getVault();
        int256 liquidatorPositionSizeBefore = vault.getPositionSize(params.marketId, liquidator);
        vault.settlePosition(
            IVault.SettlePositionParams({
                marketId: params.marketId,
                taker: params.trader,
                maker: liquidator,
                takerPositionSize: result.liquidatedPositionSizeDelta,
                takerOpenNotional: result.liquidatedPositionNotionalDelta,
                reason: PositionChangedReason.Liquidate
            })
        );
        vault.transferMargin(params.marketId, params.trader, liquidator, result.feeToLiquidator);
        vault.transferMargin(params.marketId, params.trader, address(this), result.feeToProtocol);

        // always check margin in the end
        _checkMarginRequirement(
            CheckMarginRequirementParams({
                vault: vault,
                marketId: params.marketId,
                trader: liquidator,
                price: mmProfile.price,
                isReducing: LibPosition.isReduceOnly(
                    liquidatorPositionSizeBefore,
                    vault.getPositionSize(params.marketId, liquidator)
                )
            })
        );
        _emitLiquidatedEvent(
            EmitLiquidatedEventParams({
                marketId: params.marketId,
                liquidator: liquidator,
                trader: params.trader,
                positionSizeDelta: result.liquidatedPositionSizeDelta,
                positionNotionalDelta: result.liquidatedPositionNotionalDelta,
                price: mmProfile.price,
                penalty: result.penalty,
                liquidationFeeToLiquidator: result.feeToLiquidator,
                liquidationFeeToProtocol: result.feeToProtocol
            })
        );
        return (result.liquidatedPositionSizeDelta, result.liquidatedPositionNotionalDelta);
    }

```
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L161-L223

## Tool used

Manual Review

## Recommendation

- Use pull method to withdraw user's funds whenever they want instead of adding this logic in liquidation function.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  the user is required to transfer the margin already when openning a position, so there is no user(his address) interaction during liquidation, which means even if the transfer will happen, it will be b/w the vault and the liquidator not the initial trader.

**Comment by nevillehuang** [comment]
Invalid, the funds is transferred from the vault to the liquidator, not directly freom the user getting liquidator as seen [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L193-L194)
