### ISSUE TITLE
Bauer - The deposit() and withdraw() functions lack slippage protection

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#57]
Bauer

high

# The deposit() and withdraw() functions lack slippage protection

## Summary
The `deposit()` and `withdraw()` functions lack slippage protection, which can result in financial losses for users if the price is manipulated.

## Vulnerability Detail
The `OracleMaker.deposit()` function allows users to deposit collateral and receive shares. When calculating the amount of collateral a user will receive, the protocol first obtains the price from the Pyth oracle. 
```solidity
uint256 price = _getPrice();

```

Next, it calculates the account value of the contract using the formula: `account value = margin + positionSize * price + openNotional`. 
```solidity
      uint256 vaultValueXShareDecimals = _getVaultValueSafe(vault, price).formatDecimals(
                INTERNAL_DECIMALS,
                shareDecimals
            );

```

```solidity
   function getAccountValue(uint256 marketId, address trader, uint256 price) public view returns (int256) {
        return getMargin(marketId, trader) + getUnrealizedPnl(marketId, trader, price);
    }
```

Then, it calculates the shares for the user based on the proportion of the user's input amount relative to the account value multiplied by the total supply. 
```solidity
        _mint(depositor, shares);

```

Finally, it mints the shares and assigns them to the user.

The issue arises when the price is manipulated, resulting in a potentially inflated value for `positionsize * price` and consequently increasing the account value. This, in turn, leads to a smaller proportion of shares being calculated for the user, resulting in a loss of funds for the user.
The same issue exists in the withdraw() function.

## Impact
Loss of user funds.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L175-L226

## Tool used

Manual Review

## Recommendation
To address this issue, it is recommended to add a parameter within the function to introduce slippage protection.

Duplicate of #121

**Comment by sherlock-admin3** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  no slippage needed.
