### ISSUE TITLE
santipu_ - Underwater positions won't be liquidated when the PnL pool is empty

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#63]
santipu_

high

# Underwater positions won't be liquidated when the PnL pool is empty

## Summary

When a position has created bad debt and must be liquidated and the PnL pool is empty, liquidators won't be incentivized to liquidate that position because they won't be able to withdraw the profits of the liquidation in the same transaction.

## Vulnerability Detail

When a position has to be liquidated, anyone can call the function `ClearingHouse.liquidate` to liquidate it and earn a fee that will be settled from the PnL pool. This fee will be transferred from the margin of the liquidated account to the liquidator's margin. 

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L193
```solidity
vault.transferMargin(params.marketId, params.trader, liquidator, result.feeToLiquidator);
```

In cases where the trader doesn't have enough margin to pay the liquidator fee, it will create bad debt on the protocol. When a liquidation generates bad debt and the PnL pool is empty, the liquidator won't receive the fee but it will be added as an unsettled margin on his account. 

The function `vault.transferMargin` will call `_settlePnl`:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L214-L222
```solidity
_settlePnl(marketId, from, -(amount.toInt256()));
_settlePnl(marketId, to, amount.toInt256());
```

And the function `_settlePnl` will call [`settlePnl`](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/LibPositionModel.sol#L19-L67), that will try to transfer the margin between the liquidated trader and the liquidator, using the PnL pool in between. In cases where the trader doesn't have enough margin and the PnL pool is empty, the liquidator won't have the margin increased, but that value will be stored in `unsettledMargin`.

When a liquidator has the fee added to `unsettledMargin` instead of margin, it won't be able to withdraw that fee because it will have to wait for the PnL pool to increase. The issue is that the liquidator doesn't know if the PnL pool is going to be replenished again, therefore it won't risk liquidating an underwater position in this scenario. 

Given that the liquidators are always bots that seek only profits, a liquidator won't be willing to spend funds to liquidate an account if there are not going to be instant profits on the same transaction.

## Impact

Positions that are underwater when the PnL pool is empty won't be liquidated because liquidators won't receive the fee in the same transaction. This will cause the position isn't liquidated when it should be and it may create more bad debt for the protocol if the market continues to move against that position. 

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L193-L193

## Tool used

Manual Review

## Recommendation

To mitigate this issue, is recommended to create a special mechanism that will always give the fee to liquidators, even if the PnL pool is empty at that moment. This mitigation is crucial because if underwater positions are not liquidated on time, is possible that they will create even more bad debt, which will hurt the protocol's health.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  this seem to be a know issue as per readMe "PnL Pool currently starts empty, so a trader with realized gains may experience temporary illiquidity when he tries to withdraw those gains. This inconvenience will be mitigated in the future with a buffer balance"

**Comment by Wraecca** [comment]
this is more a design-choice instead of security issue, the recommendation breaks the purpose of pnl pool. if it pays fee to liquidator even if pnl pool is 0, this money must comes from other account's margin. which means when an attack creates a significant bad debt, the entire market is drained.

as we listed in known issue, we think it's better to provide a buffer balance in the future instead of using other user's fund and break the purpose of pnl pool.

**Comment by santipu03** [comment]
Escalate 

I think this issue should be MEDIUM severity as per the Sherlock rules:

> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

In this case, when the scenario described in the report is given (position has to be liquidated with bad debt and PnL pool is empty), it will cause a loss of funds because positions won't get liquidated and more bad debt will be generated. 

The known issues section states the following:

> PnL Pool currently starts empty, so a trader with realized gains may experience temporary illiquidity when he tries to withdraw those gains. This inconvenience will be mitigated in the future with a buffer balance

However, I don't think this issue falls into a known issue because the impact is unexpected and not described within the statement above. The known issue describes the scenario where a trader may experience temporary illiquidity when he tries to withdraw funds, but that doesn't relate to this issue, that is about some positions not getting liquidated.

The impact of this issue is far greater and unexpected and is breaking a core invariant of the Perpetual protocol, that unhealthy positions should get liquidated ASAP to avoid bad debt. 

I'd like to know the opinion of @Czar102 about this but I think this issue should be valid.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> I think this issue should be MEDIUM severity as per the Sherlock rules:
> 
> > Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.
> 
> In this case, when the scenario described in the report is given (position has to be liquidated with bad debt and PnL pool is empty), it will cause a loss of funds because positions won't get liquidated and more bad debt will be generated. 
> 
> The known issues section states the following:
> 
> > PnL Pool currently starts empty, so a trader with realized gains may experience temporary illiquidity when he tries to withdraw those gains. This inconvenience will be mitigated in the future with a buffer balance
> 
> However, I don't think this issue falls into a known issue because the impact is unexpected and not described within the statement above. The known issue describes the scenario where a trader may experience temporary illiquidity when he tries to withdraw funds, but that doesn't relate to this issue, that is about some positions not getting liquidated.
> 
> The impact of this issue is far greater and unexpected and is breaking a core invariant of the Perpetual protocol, that unhealthy positions should get liquidated ASAP to avoid bad debt. 
> 
> I'd like to know the opinion of @Czar102 about this but I think this issue should be valid. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Agree with sponsor comments [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/63#issuecomment-2017420835), I believe this issue should remain invalid as it is already a issue that has been considered, albeit the impact wasn't explicitly highlighted. A workaround was already mentioned by utilizing a buffer balance to resolve the issue.

**Comment by santipu03** [comment]
Regarding the sponsor's comment:

> the recommendation breaks the purpose of pnl pool. if it pays fee to liquidator even if pnl pool is 0, this money must comes from other account's margin. which means when an attack creates a significant bad debt, the entire market is drained.

My recommendation on the report it was just an idea, but it should not define the validity of this issue.

> as we listed in known issue, we think it's better to provide a buffer balance in the future instead of using other user's fund and break the purpose of pnl pool.

The README mentioned that the team was aware of a scenario where the PnL pool is empty, leading the traders to experience temporary illiquidity when trying to withdraw profits. However, that does not mean that the team was aware of other potential consequences when this scenario happened. The team accepted the risk that traders experience temporary illiquidity, not that the protocol generates bad debt. 

@nevillehuang 
There was an issue in a recent contest with a scenario similar to this one that was judged valid, it's [here](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/196).

**Comment by WangSecurity** [comment]
I agree that this should remain invalid since it's a known issue. Yes, the explicit scenario of the liquidators is not mentioned, but the solution of buffer balance proposed by the sponsor (in the README) will mitigate this issue. Moreover, the liquidations can still occur, just the reward for them will be distributed later. Hence, planning to reject the escalation and leave the issue as it is.

Small remark, under Sherlock's rules, "Historical decisions are not considered sources of truth".

**Comment by santipu03** [comment]
> Moreover, the liquidations can still occur, just the reward for them will be distributed later.

In a liquidation, the liquidator must see profit in the same transaction or it won't execute the liquidation, that's how bots usually work. I thought this issue could be considered valid by reading this part of the Sherlock docs:

> Exception: Sometimes the README would take a wider group of impact/issue types out of scope than intended. In those cases, Sherlock may decide to consider an issue valid, while it would otherwise be considered out of scope.

I think this case may apply here given the critical impact this issue could have if triggered, causing positions to create bad debt within the protocol.

**Comment by IllIllI000** [comment]
The liquidator will see the profit in their vault account value. Withdrawing from the vault is a separate operation, which they normally wouldn't do since it would require spending more gas, and would require them to re-deposit in order to do more liquidations.

**Comment by WangSecurity** [comment]
I don't think this rule can be applied here:

> Exception: Sometimes the README would take a wider group of impact/issue types out of scope than intended. In those cases, Sherlock may decide to consider an issue valid, while it would otherwise be considered out of scope.

As I've said, the liquidations can still go through successfully and not revert. Also, the above comment correctly stated:

> The liquidator will see the profit in their vault account value. Withdrawing from the vault is a separate operation

Hence, I stand by my points laid out above.

**Comment by santipu03** [comment]
The liquidations won't revert but nobody will execute them if there's not a reward in the same transaction, that's how the liquidators work. 

If the protocol arrives at a point of having the PnL pool empty, there's no guarantee that it will be filled again soon. Thus, if there's no incentive for executing a liquidation, it won't get executed causing even more bad debt on the protocol.

**Comment by WangSecurity** [comment]
I believe "nobody will execute them if there's not a reward in the same transaction" is an assumption and as it's mentioned in the README, the protocol team already have the solution in a form of "buffer balance". Hence, my decision remains the same: reject the escalation and leave the issue as it.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/63/#issuecomment-2037745262): rejected
