### ISSUE TITLE
santipu_ - Funding rate not accounting for unrealized PnL on `OracleMaker` leads to inaccurate funding fee

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#67]
santipu_

medium

# Funding rate not accounting for unrealized PnL on `OracleMaker` leads to inaccurate funding fee

## Summary

The margin of `OracleMaker` is key to calculating the funding rate. Essentially, a larger margin means a lower funding rate, and a smaller margin results in a higher rate. However, the margin is not taking into account the unrealized PnL of `OracleMaker`, and this will cause a great variance in the funding fee if the maker hasn't settled a position in a while.

## Vulnerability Detail

The purpose of the funding fee is to reward positions that are in the same direction as `OracleMaker` and make pay for positions that are in the opposite direction. The funding rate is calculated as the following:

$$
\begin{aligned}
maxCapacity &:= \frac{OracleMakerMargin}{minMarginRatio}
\\\\\\
imbalanceRatio &:= \frac{abs(OracleMakerOpenNotional)^{exp}}{maxCapacity} 
\\\\\\
fundingRate &:= fundingFactor \times imbalanceRatio
\end{aligned}
$$

In the actual implementation of the funding rate, the margin of `OracleMaker` does not include the pending margin (funding fee and borrowing fee) because it would result in an infinite loop dependency. This is stated in the code comments:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/fundingFee/FundingFee.sol#L120-L123
```solidity
// we can only use margin without pendingMargin as totalDepositedAmount
// since pendingMargin includes pending borrowingFee and fundingFee,
// it will be infinite loop dependency
uint256 totalDepositedAmount = uint256(_getVault().getSettledMargin(marketId, fundingConfig.basePool));
```

_*in the code, `totalDepositedAmount` is the variable that holds the `OracleMaker` margin._ 

However, the implementation is only getting `settledMargin` for calculating the `OracleMaker` margin, forgetting about the unrealized PnL. **The unrealized profits and losses are key for the margin calculation because they add or subtract the amount of profits/losses accumulated since the last position has been settled on the maker.** 

When we don't include the unrealized PnL on the `OracleMaker` margin, we're not including the profits or losses that the maker has incurred since the last position was settled on `OracleMaker`. If the price has changed since then, these extra profits/losses will not be accounted for on the funding rate, resulting in an inaccurate rate, potentially damaging the risk exposure on the `OracleMaker`. 

## Impact

When `OracleMaker` hasn't settled a position in a while and prices have changed, the unrealized PnL of `OracleMaker` won't be taken into account in the calculation of the funding fee. This will result in an inaccurate funding rate that will hurt the risk exposure of the `OracleMaker`. 

For example, when `OracleMaker` has some unrealized losses, those won't be accounted for in the margin when calculating the funding rate. Therefore, the final funding rate will be lower than it should be, charging a lower fee for positions that are opposite to the `OracleMaker`, not incentivizing enough to close them. The main purpose of the funding fee is to reduce the risk exposure on `OracleMaker` (not too long or too short), when the funding rate is not high enough that will hurt the risk exposure of `OracleMaker`, causing losses to the LPs. 

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/fundingFee/FundingFee.sol#L123

## Tool used

Manual Review

## Recommendation

To mitigate this issue is crucial to account for the unrealized PnL of `OracleMaker` in the calculation of the funding rate. Below is the pseudo-code of a possible implementation:

```diff
    function getCurrentFundingRate(uint256 marketId) public view returns (int256) {
        // ...

        // we can only use margin without pendingMargin as totalDepositedAmount
        // since pendingMargin includes pending borrowingFee and fundingFee,
        // it will be infinite loop dependency
        uint256 totalDepositedAmount = uint256(_getVault().getSettledMargin(marketId, fundingConfig.basePool));
+       int256 unrealizedPnL = _getVault().getUnrealizedPnl(marketId, fundingConfig.basePool, price);
+       totalDepositedAmount += unrealizedPnL;
        uint256 maxCapacity = FixedPointMathLib.divWad(
            totalDepositedAmount,
            uint256(OracleMaker(fundingConfig.basePool).minMarginRatio())
        );

        // ...
    }
```

The actual mitigation should include the correct type conversions, as well as the correct pyth price to get the unrealized PnL.

**Comment by sherlock-admin2** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  valid; medium(8)

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/perpetual-protocol/perp-contract-v3/pull/15

**Comment by IllIllI000** [comment]
@nevillehuang The funding fee calculation is shown [here](https://perp.notion.site/Long-Short-Skew-Funding-Fee-fd7af74f74644209baf0ffb562dc4271) and the code matches the calculation. The listed formula is `maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio` and this submission is suggesting to change it to `maxCapacity = (basePool.totalDepositedAmount + unrealizedpnl) / basePool.minMarginRatio`, which is a design decision, not a security issue.

**Comment by nevillehuang** [comment]
See comments [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68#issuecomment-2030170900) and agree with @IllIllI000 comments [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/67#issuecomment-2030177214)

**Comment by santipu03** [comment]
Escalate

This issue should be MEDIUM. 

I disagree with the LSW comments. The fact that the variable names on the code match the documentation's variable names does not mean that the actual value of those variables is accurate.

The docs have the following formula for calculating `maxCapacity`:
```
maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio
```

The variable `basePool.totalDepositedAmount` just represents the current margin of OracleMaker (base pool). This is because the variable `maxCapacity` represents the maximum open notional the OracleMaker can have, and therefore it must use the current OracleMaker's margin, and that includes the unrealized PnL. 

When not including the unrealized PnL on the `totalDepositedAmount` variable, the funding fee will be inaccurate because it won't take into account the last price changes. In a scenario where the OracleMaker hasn't been settled in a while and prices rapidly change, the funding fee won't reflect those price changes, charging an inaccurate funding fee to users and causing loss of funds. 

When the funding rate is inaccurate, we can have two scenarios:

1. **Funding rate is higher than it should be**: In this case, all positions that are against the OracleMaker's position will be charged a higher funding fee, therefore pushing some positions into liquidation. 
2. **Funding rate is lower than it should be**: In this case, positions that are against the OracleMaker's position will be charged a lower funding fee, therefore hurting the risk exposure on OracleMaker, causing losses to the LPs.  

I don't consider this issue a design decision, but a security issue that will lead to loss of funds if not dealt with. Moreover, the sponsors already confirmed the issue and fixed it, confirming my point. 

I'd like to ask the Lead Judge to reevaluate the severity of this issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue should be MEDIUM. 
> 
> I disagree with the LSW comments. The fact that the variable names on the code match the documentation's variable names does not mean that the actual value of those variables is accurate.
> 
> The docs have the following formula for calculating `maxCapacity`:
> ```
> maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio
> ```
> 
> The variable `basePool.totalDepositedAmount` just represents the current margin of OracleMaker (base pool). This is because the variable `maxCapacity` represents the maximum open notional the OracleMaker can have, and therefore it must use the current OracleMaker's margin, and that includes the unrealized PnL. 
> 
> When not including the unrealized PnL on the `totalDepositedAmount` variable, the funding fee will be inaccurate because it won't take into account the last price changes. In a scenario where the OracleMaker hasn't been settled in a while and prices rapidly change, the funding fee won't reflect those price changes, charging an inaccurate funding fee to users and causing loss of funds. 
> 
> When the funding rate is inaccurate, we can have two scenarios:
> 
> 1. **Funding rate is higher than it should be**: In this case, all positions that are against the OracleMaker's position will be charged a higher funding fee, therefore pushing some positions into liquidation. 
> 2. **Funding rate is lower than it should be**: In this case, positions that are against the OracleMaker's position will be charged a lower funding fee, therefore hurting the risk exposure on OracleMaker, causing losses to the LPs.  
> 
> I don't consider this issue a design decision, but a security issue that will lead to loss of funds if not dealt with. Moreover, the sponsors already confirmed the issue and fixed it, confirming my point. 
> 
> I'd like to ask the Lead Judge to reevaluate the severity of this issue. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68#issuecomment-2046230838)

**Comment by WangSecurity** [comment]
I agree with the comment by @IllIllI000 above. This report is a design improvement to calculation of the funding fee. LSW's comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68#issuecomment-2058757004) shows that there several ways to account the fees, each with their benefits and trade-offs. Hence, I believe it's not a security issue, but the design advice.

Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/67/#issuecomment-2037604978): rejected

**Comment by IllIllI000** [comment]
The sponsor acknowledges that `getNextFundingRate()` will return the wrong value if base pool has a negative account value, and thus the funding fee in that case will be wrong. The sponsor plans to disable the funding rate in this release, and will address the issue in a future upgrade if possible

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
