### ISSUE TITLE
santipu_ - The position rate on `OracleMaker` is not including unrealized profits, which will penalize extra hard traders that may increase long/short exposure

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#69]
santipu_

medium

# The position rate on `OracleMaker` is not including unrealized profits, which will penalize extra hard traders that may increase long/short exposure

## Summary

The `OracleMaker` has a pricing system to penalize traders that increase the maker's position by offering a slightly worse price than the market price. This system is designed to discourage traders that aim to increase the long/short exposure on the maker. The mechanism, however, is flawed because it doesn't account for unrealized profits on the maker's margin, penalizing extra hard traders that increase the maker's position. 

## Vulnerability Detail

When a trader wants to settle an order with `OracleMaker`, the function `OracleMaker.fillOrder` will be called. This function will calculate the price with spread, which will be the price that the trader will have its order filled with. Here is the function:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L265-L310

```solidity
    function fillOrder(
        bool isBaseToQuote,
        bool isExactInput,
        uint256 amount,
        bytes calldata
    ) external onlyClearingHouse returns (uint256, bytes memory) {
        uint256 basePrice = _getPrice();
>>      uint256 basePriceWithSpread = _getBasePriceWithSpread(basePrice, isBaseToQuote);

        // ...
    }
```

The function `_getBasePriceWithSpread` will calculate the price with the spread that will be applied to the order settlement. To calculate the spread, it will first calculate the position rate, which is defined by the following formulas:

$$
\begin{aligned}
\\
\text{maxPositionNotional} &:= \frac{\min(\text{unsettledMargin}, \text{accountValue})}{\text{minMarginRatio}} 
\\\\
\text{uncappedPositionRate} &:= -\frac{\text{openNotional}}{\text{maxPositionNotional}}
\\\\
\text{positionRate} &:= 
\begin{cases} 
\min(\text{uncappedPositionRate}, 1) & \text{if } \text{uncappedPositionRate} > 0 \\
\max(\text{uncappedPositionRate}, -1) & \text{otherwise}
\end{cases}
\\\\
\end{aligned}
$$

These formulas are applied to the function `OracleMaker._getPositionRate`:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L411-L437

```solidity
    function _getPositionRate(uint256 price) internal view returns (int256) {
        IVault vault = _getVault();
        uint256 marketId_ = _getOracleMakerStorage().marketId;
        int256 accountValue = vault.getAccountValue(marketId_, address(this), price);
        int256 unrealizedPnl = vault.getUnrealizedPnl(marketId_, address(this), price);
        int256 unsettledMargin = accountValue - unrealizedPnl;
        int256 collateralForOpen = FixedPointMathLib.min(unsettledMargin, accountValue);
        // TODO: use positionMarginRequirement
        //int256 collateralForOpen = positionMarginRequirement + freeCollateralForOpen;
        if (collateralForOpen <= 0) {
            revert LibError.NegativeOrZeroMargin();
        }

        int256 maxPositionNotional = (collateralForOpen * 1 ether) / _getOracleMakerStorage().minMarginRatio.toInt256();

        // if maker has long position, positionRate > 0
        // if maker has short position, positionRate < 0
        int256 openNotional = vault.getOpenNotional(marketId_, address(this));
        int256 uncappedPositionRate = (-openNotional * 1 ether) / maxPositionNotional;

        // util ratio: 0 ~ 1
        // position rate: -1 ~ 1
        return
            uncappedPositionRate > 0
                ? FixedPointMathLib.min(uncappedPositionRate, 1 ether)
                : FixedPointMathLib.max(uncappedPositionRate, -1 ether);
    }
```

The issue here is the numerator of $maxPositionNotional$. By setting the numerator to $\min(unsettledMargin, accountValue)$ instead of just $accountValue$, we're not accounting for the unrealized profits of `OracleMaker`. 

In a scenario where `OracleMaker` has some amount of unrealized profits, $maxPositionNotional$ will be a lower value than it should be, and that will lead to $uncappedPositionRate$ being a higher value, resulting in a higher position rate. When the position rate is higher because it doesn't account for unrealized profits, traders that may increase the position size of `OracleMaker` will be offered a price way worse than the market price, leading to losses for those opened positions. 

## Impact

When `OracleMaker` has some amount of unrealized profits on its margin due to price changes, those profits won't be accounted for in the price spread. This will cause the price spread to be bigger than it should be, offering a worse price to traders that are increasing the maker's position. 

When the price spread becomes too big due to these unrealized profits, these traders will be penalized extra hard for trading. This will result in positions being created with a price too distant from the market price, causing losses to those traders when they close their positions. 

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L417

## Tool used

Manual Review

## Recommendation

To mitigate this issue is recommended to include the unrealized profits of the maker in the calculations for the position rate. That will fix the current issue and will offer traders a fair price for opening positions, a price not too distant from the current market price:

```diff

    function _getPositionRate(uint256 price) internal view returns (int256) {
        IVault vault = _getVault();
        uint256 marketId_ = _getOracleMakerStorage().marketId;
        int256 accountValue = vault.getAccountValue(marketId_, address(this), price);
        int256 unrealizedPnl = vault.getUnrealizedPnl(marketId_, address(this), price);
        int256 unsettledMargin = accountValue - unrealizedPnl;
-       int256 collateralForOpen = FixedPointMathLib.min(unsettledMargin, accountValue);
+       int256 collateralForOpen = accountValue;
        // TODO: use positionMarginRequirement
        //int256 collateralForOpen = positionMarginRequirement + freeCollateralForOpen;
        if (collateralForOpen <= 0) {
            revert LibError.NegativeOrZeroMargin();
        }

        // ...
    }
```

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  seem valid and should take into account the unrealized profits; medium(7)

**Comment by CheshireCatNick** [comment]
Originally we designed it this way just to be more conservative. It is also more consistent with our clearing house design: unrealized profit cannot be used as collateral to open position. Consider a case where the oracle maker has a huge unrealized profit. If we only use `accountValue` as `collateralForOpen`, it will have a very low position rate, but it cannot take any extra position due to clearing house restriction.

But after checking this issue, we had another discussion and agreed that inconsistency between oracle maker and clearing house is acceptable. In the end, maker is the one to decide what's the risk it is willing to take. Allowing it to take more position when it has unrealized profit does not increase any risk and seems pretty reasonable. So we will fix it as suggested.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/perpetual-protocol/perp-contract-v3/pull/9

**Comment by IllIllI000** [comment]
@nevillehuang I believe this is a design decision rather than a security issue, @CheshireCatNick please correct me if I'm misunderstanding

**Comment by CheshireCatNick** [comment]
@IllIllI000 Yes it's a design decision. We can choose between using `accountValue` (more aggressive, take more risk when having unrealized profit) v.s. `min(accountValue, unsettledMargin)` (makes oracle maker more conservative). The original design is actually more convervative.

**Comment by nevillehuang** [comment]
@IllIllI000 Is there anywhere that points to this being a design decision? Since a fix was implemented, I am inclined to keep valid. @CheshireCatNick is the fixes similar in #68 and #67, and could they be duplicates?

**Comment by IllIllI000** [comment]
@nevillehuang the OracleMaker is owned by the protocol and is present in order to provide liquidity. The design is such that it attempts to keep its position flat by giving traders who try to push it further _away_ from having a flat position, by giving them a _worse_ price. The worse price is not a guarantee that someone _won't_ trade, and is definitely not a direct incentive to get someone else to push its position in the _right_ direction. It's a design decision on whether to make the penalty smaller if there's a profit, just as it would be to arbitrarily double the result of the penalty formula they use. The protocol isn't losing money by keeping the larger disincentive, and nobody is forced to trade at the larger disincentive if they don't want to, so nobody is losing money.

**Comment by IllIllI000** [comment]
As for the others you pointed to, not including the PnL in the other incentive formulas is also a design decision. It is a perfectly valid design to not update rates for the OracleMaker until someone new trades with the OracleMaker, and that's the underlying issue that all three of these issues are pointing to. Even with the fixes, if nobody does any trades while the price is moving, the Makers will still be in the same scenario, that they have unrealized PnL that doesn't get applied to the funding rate. `Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational` https://docs.sherlock.xyz/audits/judging/judging

**Comment by nevillehuang** [comment]
Based on above discussions, since there were no inconsistencies with original documentation regarding inclusion of unrealized profits, and in fact the original design was more conservative based on this [comment here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/69#issuecomment-2022061326), I believe we can close this issue.

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
