### ISSUE TITLE
Ragnark_323 - ClearingHouse Upgradable Contract Not Using IERC20Upgradeable Interface

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#72]
Ragnark_323

medium

# ClearingHouse Upgradable Contract Not Using IERC20Upgradeable Interface

## Summary
The ClearingHouse upgradable contract, is not using the IERC20Upgradeable interface designed for upgradable contracts. This could limit the contract's future flexibility and adaptability.

## Vulnerability Detail
The [ClearingHouse](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol) contract, which is an upgradable contract.does not import or use the IERC20Upgradeable interface, which is designed for upgradable contracts.This could limit the contract's ability to be upgraded in the future, potentially impacting its flexibility and adaptability. It's recommended to use IERC20Upgradeable for upgradable contracts.

## Impact
can limit the contract's flexibility and adaptability in the future and If there is a need to upgrade the contract's functionality or fix a bug in the future, it may not be possible without redeploying the contract and migrating its state, which could be costly and time-consuming.
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L29
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol

## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, ERC20s are USDT/USDC, no need to use upgradeable contracts
