### ISSUE TITLE
Ragnark_323 - Potential Negative value for maintenanceMarginRequirement

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#73]
Ragnark_323

high

# Potential Negative value for maintenanceMarginRequirement

## Summary
The `maintenanceMarginRequirement` in [LibLiquidation.sol](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol) is declared as int256, potentially allowing negative values. This could lead to unexpected behavior, such as preventing positions from being liquidated. 

## Vulnerability Detail
In the `LibLiquidation.sol` file, the [maintenanceMarginRequirement]()https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L14C5-L14C41field in the `MaintenanceMarginProfile`truct is declared as an int256. This could potentially allow for negative values, which may lead to unexpected behavior in the contract.

The [maintenanceMarginRequirement](file:///mnt/web3/bug%20bounty/sherlock/2024-02-perpetual-NishantKoyalwar-main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#14%2C12-14%2C12) represents the minimum amount of equity that must be maintained in the margin account. If it were less than zero, it would imply that the account could go into debt beyond the value of the assets held, which is typically not allowed in margin trading systems.

If, due to some error or oversight, the `maintenanceMarginRequirement` were to become negative, it could lead to unexpected behavior in the contract. For example, in the [getLiquidatablePositionSize](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L91), if [maintenanceMarginRequirement](file:///mnt/web3/bug%20bounty/sherlock/2024-02-perpetual-NishantKoyalwar-main/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#14%2C12-14%2C12) is negative, the condition `self.accountValue >= self.maintenanceMarginRequirement` would always be true, preventing any position from being liquidated.

Moreover, the insolvency case, where `accountValue` is less than zero, is indirectly handled by the following code block:
```solidity
if (self.accountValue < self.maintenanceMarginRequirement / 2) {
    return self.positionSize;
}
```

However, if `maintenanceMarginRequirement` is less than zero, this could lead to positions not being liquidated when they should be, as the function would return a liquidatable amount of zero.

## Impact
 it could prevent positions from being liquidated when they should be. This could lead to accounts going into debt beyond the value of their held assets, which is typically not allowed in margin trading systems. The issue could potentially disrupt the normal operation of the contract and lead to financial losses.
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L14
https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/clearingHouse/LibLiquidation.sol#L110C8-L112C10
## Tool used

Manual Review

## Recommendation
Consider changing the `maintenanceMarginRequirement` field to `uint256` to prevent it from taking negative values. This would ensure that the margin requirement is always a positive value, preventing the potential issues outlined above.

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid - It will never be negative because is always get from vault.getMarginRequirement(), that returns a uint

**takarez** commented:
>  but its a fluctuating value which means it can be any number.

**Comment by nevillehuang** [comment]
Invalid, agree with santipu's comments
