### ISSUE TITLE
cu5t0mPe0 - When the Market is not active, funding fees and borrowing will still be calculated.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#74]
cu5t0mPe0

medium

# When the Market is not active, funding fees and borrowing will still be calculated.

## Summary

When the Market is inactive, the borrow fee and fund fee will still be calculated.

## Vulnerability Detail

Calculation process of borrow fee:

1. Calculate global costs
2. Use the caching mechanism to subtract the last global fee paid from the current global fee.

Then the global fee is through the formula: maxBorrowingFeeRate ***** secondsSinceLastUpdated ***** utilRatio

Therefore, if the value of secondsSinceLastUpdated is paused, it will become larger, so when the Market is inactive, the value will still become larger.

The following is the relevant code for global cost calculation:

```solidity
    function getPayerFeeGrowthGlobalDelta(BorrowingFeeState storage self) internal view returns (uint256) {
        // incrementalFeeGrowth = borrowingFeeRate * period
        // borrowingFeeRate = utilRatio * maxBorrowingFeeRate
        uint256 utilRatio = self.utilRatio;
        if (utilRatio > WAD) {
            revert LibError.InvalidRatio(utilRatio);
        }

        uint256 secondsSinceLastUpdated = self.feeGrowthGlobal.secondsSinceLastUpdated();
        if (secondsSinceLastUpdated == 0) {
            return 0;
        }

        // normally, utilRatio * maxBorrowingFeeRate should divide by WAD again, but the result we're returning
        // are also multiplied by WAD so we skip this divide
        return self.maxBorrowingFeeRate * secondsSinceLastUpdated * utilRatio;
    }
```

The following is the logic code that users need to pay global fees:

```solidity
    function syncPayerFeeGrowth(BorrowingFeeState storage self, address payer) internal {
        self.payerFeeGrowthMap[payer] = self.feeGrowthGlobal.payer;
    }
    
    function getPendingPayerFee(
        BorrowingFeeState storage self,
        address payer,
        uint256 payerOpenNotionalAbs
    ) internal view returns (int256) {
        // how to calculate feeGrowthDelta:
        // 1. get fee growth global delta since last updated
        // 2. get local fee growth from payerMap (it's the growth global stored when payer updated last time)
        // 3. calculate the difference
        uint256 oldFeeGrowthGlobal = self.feeGrowthGlobal.payer;
        uint256 feeGrowthGlobalDelta = self.getPayerFeeGrowthGlobalDelta();
        uint256 newFeeGrowthGlobal = oldFeeGrowthGlobal + feeGrowthGlobalDelta;
        uint256 feeGrowthLocal = self.payerFeeGrowthMap[payer];
        // payer always pay, fee is always growing, global is always later than local, hence feeGrowthGlobal is always
        // greater than or equals to feeGrowthLocal
        uint256 feeGrowthLocalDelta = newFeeGrowthGlobal - feeGrowthLocal;
        if (feeGrowthLocalDelta == 0) {
            return 0;
        }

        // pendingPayerFee = feeGrowthLocalDelta * payerOpenNotional
        // feeGrowthLocalDelta is multiplied by WAD by definition
        // so besides dividing WAD during multiplying with receiverOpenNotionalAbs, we divide WAD once more
        uint256 pendingPayerFee = feeGrowthLocalDelta.mulWad(payerOpenNotionalAbs) / WAD;
        return pendingPayerFee.toInt256();
    }
```

The calculation of fund fee is somewhat similar to that of borrow fee. Fund fee is also updated through (current time - last update time).

Therefore, even if the current Market is inactive, the borrow fee that the user needs to pay will be calculated. This is not stated in the document, and this is unfair to the user, because the user cannot make any transactions during this process. Action, users can only be forced to accept these fees.

And users may be liquidated as a result.

## Impact

Users will suffer additional fees or be liquidated

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/borrowingFee/LibBorrowingFee.sol#L106-L122

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/fundingFee/FundingFee.sol#L162-L177

## Tool used

Manual Review

## Recommendation

You can try adding a state variable to record the pending fee, record it during the inactive market period, update the last recording time, and then update the recording time again during the market active period.

Duplicate of #59

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid following Sherlock rules because admin is TRUSTED.
