### ISSUE TITLE
PUSH0 - Global deposit cap cannot reflect per-asset liquidity

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#76]
PUSH0

medium

# Global deposit cap cannot reflect per-asset liquidity

## Summary

While there is a cap for total collateral deposited to the Vault, there is no cap for total absolute position size for each market. The total Vault deposit cap cannot reflect the external liquidity of all markets at once.

A market that has a total position size of too large will bring difficulties and may discourage liquidations.

## Vulnerability Detail

While there is a deposit cap for the Vault (and thus caps the total margin amount), there is no cap for how much positions can be opened per market. That simply means the entire market (or the majority of it) can choose to open positions against the most illiquid supported asset on the chain.

This alone does not pose a problem yet for a perpetual exchange, but due to the protocol's reliant on external liquidity, we show why liquidations may be discouraged on illiquid assets.

### On liquidation

The key that incentivizes liquidating is the guaranteed profit without risk exposure: The liquidator must be able to immediately close their position.
- If the liquidator keeps their position, their margin is exposed to that asset's price. Considering that the price movement was already unfavorable, pushing the position to being liquidated to begin with, then holding the position in their place is a very risky move.

Currently, the only way to close a position right away is through opening an opposite position on the SpotHedgeBasedMaker (orders towards Oracle Maker must go through the relayer). However, Different assets on UniV3 has different liquidity/TVL. Since the SpotHedgeBasedMaker performs a swap in response to an order, illiquid assets will incur more price impact when swapped.

Sending a closing order to the relayer for the Oracle Maker ASAP is also an option. However the latency between when the liquidation tx is confirmed, when the relayer receives an order, and when the tx actually goes through, may cause the PnL to outweight the liquidation bonus. The added layer of risk will discourage liquidators from using this method.
  - In case of a mass liquidation (e.g. a sharp price drop), the Oracle Maker's quoted price may have a significant spread, which will further discourage liquidators due to the added risk due to the potential loss.

Another factor to consider is that this issue fortifies itself. Since there is no cap per market, traders are actually encouraged to open positions on assets with less liquidity, since it will likely more difficult to get liquidated in time, in case of a sharp market movement.
- When the market cannot handle the liquidations, one can actually attack the protocol by opening a position against themselves on another account (p2p positions), with one side making a profit, the other side making a loss but won't get liquidated on time anyway.

To sum up, the total Vault deposit cap cannot reflect external liquidity for all supported assets. The majority of margins may be used up against more illiquid assets (e.g. LINK) rather than more liquid assets (e.g. WETH), which will cause problems when a typical sharp price movement occurs.

## Impact

Position size per market is uncapped, which will leave certain markets in a risky state during sharp market movements. When the external market fails to handle the liquidation pressure, bad debt occurs.

## Code Snippet

There is no position cap as a market-specific risk param:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/config/Config.sol#L27-L32

## Tool used

Manual Review

## Recommendation

Introduce a cap for absolute total position sizes per market, with the cap being a risk param, reflecting their volatility and on-chain liquidity. 
- Since the total signed position sizes (short and long) of a market is always zero, just checking that one side does not exceed the cap is sufficient.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Low - The protocol team is supposed to give support only to liquid markets. It seems more like a design improvement issue.

**Comment by CheshireCatNick** [comment]
- Won't fix.
- We understand that liquidator will be exposed to risk if they hold positions after liquidations. However, it's not necessary for them to close position immediately with oracle maker or spot hedge maker. They can also hedge those positions on CEX like Binance.
- It's true that markets with low liquidity might have higher risk due to high volatilities. We will definitely consider the risk by adding a position cap or limiting maximum leverage by market. Such precautions will be added when we launch such illiquid markets.

**Comment by IllIllI000** [comment]
@nevillehuang this sounds like a low: `This alone does not pose a problem yet for a perpetual exchange, but due to the protocol's reliant on external liquidity, we show why liquidations may be discouraged on illiquid assets` and the sponsor points out that liquidators can easily (and often do) hedge their positions on CEXs. Not having per-market caps in and of itself sounds like a design decision, not a security issue

**Comment by Oot2k** [comment]
escalate

Hi,
I think the report correctly points out various risks of having only a global deposit cap. 
The CEX argument does not apply here again, when considering perp as a standalone system.
In case protocol team intends to fix this in the future, in should still be considered a valid finding now.
Senior Watsons comment does not refer to any of the many impacts mentioned in the report.
I believe the report and my comment should be enough to judge this issue accordingly. 
Thanks!

**Comment by sherlock-admin2** [comment]
> escalate
> 
> Hi,
> I think the report correctly points out various risks of having only a global deposit cap. 
> The CEX argument does not apply here again, when considering perp as a standalone system.
> In case protocol team intends to fix this in the future, in should still be considered a valid finding now.
> Senior Watsons comment does not refer to any of the many impacts mentioned in the report.
> I believe the report and my comment should be enough to judge this issue accordingly. 
> Thanks! 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@Oot2k Your following statement sounds like speculation:

> This alone does not pose a problem yet for a perpetual exchange, but due to the protocol's reliant on external liquidity, we show why liquidations may be discouraged on illiquid assets.

However, it seems like any mitigations intended by the protocol towards potential risk involved should indeed have been highlighted within contest details/documentation. @IllIllI000 Is there anywhere this was indicated? If not I believe medium severity could be appropriate.

**Comment by IllIllI000** [comment]
The docs say `Liquidators: liquidate risky positions at a discounted price` https://perp.notion.site/Perp-v3-11275f0dcb914b3a992d9c7f915f2c0c . The liquidators are incentivized to liquidate in order to get that fee. Of _course_ they're going to look for ways to get that fee even if there's no liquidity on Perp, and that obviously includes CEXes where things are faster and cheaper than on-chain, in order to maximize the ~2% fee on the position being liquidated that is paid for liquidations.

**Comment by WangSecurity** [comment]
I believe this report is an improvement suggestion to make the conditions more favourable for the liquidators. Moreover, as I understand from the comments above, there are ways for the liquidators to mitigate the risk and that it's not intended to launch the illiquid markets. Hence, I believe it's not a smart contract security issue.

Planning to reject the escalation and leave the issue as it.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Oot2k](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/76/#issuecomment-2037720561): rejected
