### ISSUE TITLE
AllTooWell - The liquidition penalty to the protocol will be locked in ```ClearingHouse.sol``` forever

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#83]
AllTooWell

medium

# The liquidition penalty to the protocol will be locked in ```ClearingHouse.sol``` forever

## Summary
The liquidition penalty to the protocol will be locked in ```ClearingHouse.sol``` forever
## Vulnerability Detail
Traders need to pay liquidation penalty after liquidation, and the liquidator will receive a portion of the liquidation penalty as fee for this liquidation, while the remaining penalty will go to the protocol. The code is as follows:
```solidity
        vault.transferMargin(params.marketId, params.trader, liquidator, result.feeToLiquidator);
        vault.transferMargin(params.marketId, params.trader, address(this), result.feeToProtocol);
```
We can see the penalty to the protocol are stored in the margin which belongs to the ```ClearingHouse``` address. But in ```ClearingHouse.sol``` and ```Vault.sol``` there is no function which can be used to move the margin out. The liquidition penalty to the protocol will be locked in ```ClearingHouse.sol``` forever.
## Impact
The liquidition penalty to the protocol will be locked and not able to use.
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L193-L194
## Tool used
manual
## Recommendation
Implement a function to move the liquidition penalty out and use the penalty to develop the protocol.

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Known issue on README

**takarez** commented:
>  this is a known issue according to the ReadMe.

**Comment by nevillehuang** [comment]
Invalid, known issue

> 14. ClearingHouse may has some surplus margin (from liquidation fee) that can not be withdrawn by anyone yet
