### ISSUE TITLE
bigbick123456789000 - Lack of Proper Handling for ERC20 Token Approvals

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#86]
bigbick123456789000

medium

# Lack of Proper Handling for ERC20 Token Approvals

## Summary
The `deposit` function in the `OracleMaker` contract does not handle the approval process for ERC20 tokens properly, which can lead to issues with tokens like Tether (USDT) whose `approve()` function reverts if the current approval is not zero. This oversight can potentially disrupt the deposit process and cause unexpected failures.
## Vulnerability Detail
The `deposit` function is responsible for depositing ERC20 tokens into the contract, allowing users to mint shares in exchange for their deposited tokens. However, the function directly calls `collateralToken.approve()` without checking the current allowance. This approach can lead to problems with tokens like Tether (USDT) that require the allowance to be reset to zero before setting a new approval.
```solidity
collateralToken.approve(address(vault), amountXCD);
```
## Impact
The lack of proper handling for ERC20 token approvals in the deposit function can result in failed deposits and disruptions to the user experience. Tokens that require resetting the allowance to zero before setting a new approval, such as Tether (USDT), may cause the transaction to revert, preventing users from successfully depositing their tokens.
## Code Snippet
[OracleMaker.sol#L217](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L217)
[SpotHedgeBaseMaker.sol#L613](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L613)
## Tool used

Manual Review

## Recommendation
Always do `safeApprove(0)` if the allowance is being changed, or use `safeIncreaseAllowance()`.

Duplicate of #56

**Comment by sherlock-admin3** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid because USDT only has this weird behaviour on mainnet

**takarez** commented:
>  all the approved amount is being spent which is technically resetting it to zero
