### ISSUE TITLE
bigbick123456789000 - Orders can get stuck in cancelled state due to missing deadline check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#89]
bigbick123456789000

medium

# Orders can get stuck in cancelled state due to missing deadline check

## Summary
The `SpotHedgeBaseMaker` contract lacks a deadline check in the functions responsible for executing Uniswap V3 trades. Specifically, the `_uniswapV3ExactInput` and `_uniswapV3ExactOutput` functions do not verify that the provided deadline for the trade is set to a future timestamp greater than the current block timestamp. This omission can potentially result in orders being immediately marked as cancelled, leading to tokens getting stuck in a cancelled state.
## Vulnerability Detail
The `_uniswapV3ExactInput` and `_uniswapV3ExactOutput` functions are responsible for executing Uniswap V3 trades with exact input and exact output, respectively. However, these functions lack a crucial check to ensure that the provided deadline for the trade is set to a future timestamp.
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L598-L615

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L580-L596

These functions currently approve and execute Uniswap V3 trades without validating the deadline parameter, allowing trades with expired deadlines to be processed. As a result, orders may be immediately marked as cancelled, causing tokens to become stuck in a cancelled state.

## Impact
The lack of a deadline check in Uniswap V3 trades can lead to orders being marked as cancelled immediately after execution. This can result in tokens becoming stuck in a cancelled state, impacting the liquidity and usability of the tokens within the contract.

## Code Snippet
[SpotHedgeBaseMaker.sol#L598-L615](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L598-L615)
[SpotHedgeBaseMaker.sol#L580-L596](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L580-L596)
## Tool used

Manual Review

## Recommendation
A deadline check should be added to the `_uniswapV3ExactInput` and `_uniswapV3ExactOutput` functions to ensure that the provided deadline for the trade is set to a future timestamp greater than the current block timestamp.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  but the deadline param is right there.

**Comment by nevillehuang** [comment]
Invalid, slippage checks are sufficient, if transaciton reverts no tokens will be stuck
