### ISSUE TITLE
lemonmon - Missing check for `redeemedRatio` in `OracleMaker.withdraw()` may result in burning the withdrawer's shares without them receiving collateral tokens

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#94]
lemonmon

medium

# Missing check for `redeemedRatio` in `OracleMaker.withdraw()` may result in burning the withdrawer's shares without them receiving collateral tokens

## Summary

The function `OracleMaker.withdraw()` may burn the withdrawer's shares without checking whether the withdrawer receives any collateral tokens for their shares.

## Vulnerability Detail

When withdrawing with `OracleMaker.withdraw()` the `redeemedRatio` is calculated on line 234 in OracleMaker.sol. The calculation result may be zero if only a small amount of shares is withdrawn and `totalSupply()` is very big due to the division rounding down to 0.

If `redeemedRatio` is zero, then the amount of collateral tokens to transfer to the withdrawer which is `withdrawnAmountXCD` is calculated on line 244 and will also be zero due to multiplication with `redeemedRatio` which is zero.

As a result the `withdrawer` will receive 0 amount (`withdrawnAmountXCD`) of the `collateralToken` (line 252 OracleMaker.sol), despite that his shares are being burnt (line 237 OracleMaker.sol).

## Impact

When withdrawing from `OracleMaker` the withdrawer may receive zero collateral tokens for his shares that are burnt, suffering a loss.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L228-L259

## Tool used

Manual Review

## Recommendation

Consider reverting if `redeemedRatio` is zero inside `OracleMaker.withdraw()`:

```solidity
// OracleMaker.sol
234        uint256 redeemedRatio = shares.divWad(totalSupply());
+235       if (redeemedRatio == 0) { revert(); }
```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  invalid

**Comment by nevillehuang** [comment]
Invalid, shares are scaled up by WAD (1e18) before division, so this is highly unlikely if not not possible. Additionally, no collateral will be withdrawn given `withdrawnAmountXCD == 0`
