### ISSUE TITLE
petro1912 - cancelOrder - The order owner can cancel the order even if the order has been settled by the relayer and the position has already been created.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#99]
petro1912

medium

# cancelOrder - The order owner can cancel the order even if the order has been settled by the relayer and the position has already been created.

## Summary
The order owner can cancel the order even if the order has been settled by the relayer and the position has already been created.

## Vulnerability Detail
`cancelOrder` function of OrderGatewayV2 contract only checks `msgSender` is order owner but doesn't take any more validation like if order has already been settled, position created, order has already been cancelled, order has been expired.

`cancelOrder` function only sets `isOrderCanceled` slot as true for order key if order signature is valid.

## Impact
Inconsistencies in order matching and execution mechanisms may occur, affecting the integrity of the ordering system.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/orderGatewayV2/OrderGatewayV2.sol#L227-L237

## Tool used

Manual Review

## Recommendation
Recommend that order should not be cancelled if order has been expired/settled (position created) /cancelled already.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  low to no impact; the value only gets checked during order filling(_fillMakerOrder; _fillTakerOrder) in the _verifyOrder function and no where else.

**Comment by nevillehuang** [comment]
Invalid, checked via `_verifyOrder` [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/orderGatewayV2/OrderGatewayV2.sol#L487-L489)
